// describeForm — cache-first plain-English form description via claude-haiku-4-5.
// EDITOR or ADMIN only — writing back to forms/{formKey} requires canEdit() in rules.
// Cache-hit path returns immediately (no AI call or write). Miss path generates a
// 2-3 sentence plain-English summary and writes it back so the next caller gets an
// instant cache hit.
import { onCall, HttpsError } from 'firebase-functions/v2/https'
import { getApps, initializeApp } from 'firebase-admin/app'
import { getFirestore } from 'firebase-admin/firestore'
import { ANTHROPIC_API_KEY, anthropic, MODEL_FAST, requireRole, CACHE_1H } from './runtime'
import { auditedMerge } from './audited'
import { emptyUsage, addUsage, recordUsage } from './telemetry'

if (!getApps().length) initializeApp()

interface DescribeFormInput {
  formKey: string  // Firestore doc key inside the `forms` collection
}

export const describeForm = onCall<DescribeFormInput>(
  { secrets: [ANTHROPIC_API_KEY], maxInstances: 5 },
  async (req) => {
    if (!req.auth) throw new HttpsError('unauthenticated', 'Sign in to generate form descriptions.')
    // Mirror firestore.rules: forms/{formKey} write requires canEdit() (EDITOR | ADMIN).
    requireRole(req.auth, 'EDITOR', 'ADMIN')

    const { formKey } = req.data
    if (!formKey?.trim()) throw new HttpsError('invalid-argument', 'formKey is required.')

    const db  = getFirestore()
    const ref = db.doc(`forms/${formKey}`)
    const snap = await ref.get()
    if (!snap.exists) throw new HttpsError('not-found', `Form ${formKey} not found.`)

    const data = snap.data() as Record<string, unknown>

    // Cache hit — return immediately if a non-empty description is already stored.
    const cached = typeof data.description === 'string' && data.description.trim().length > 0
    if (cached) return { description: data.description as string, cached: true }

    // Generate a plain-English summary. We pass the structural metadata only — no
    // invented content. haiku-4-5 is the right model for this simple classification task.
    const number   = String(data.number ?? '')
    const name     = String(data.name ?? '')
    const category = String(data.category ?? '')
    const edition  = String(data.edition ?? '')
    const source   = String(data.source ?? '')
    const dynFields = Array.isArray(data.dynamicFields)
      ? (data.dynamicFields as { name: string }[]).map((f) => f.name).join(', ')
      : ''

    const prompt = [
      `Form number: ${number}`,
      `Name: ${name}`,
      `Category: ${category.replace(/_/g, ' ')}`,
      `Edition: ${edition}`,
      `Source: ${source}`,
      dynFields ? `Dynamic fields: ${dynFields}` : '',
    ].filter(Boolean).join('\n')

    const usageAccum = emptyUsage()
    const t0 = Date.now()
    let ok = true
    try {
      const msg = await anthropic().messages.create({
        model: MODEL_FAST,
        max_tokens: 200,
        // The instruction is the stable cacheable prefix (1h TTL); only the per-form metadata
        // in the user message is volatile and sits after the breakpoint. (Below Haiku's 4096
        // cache floor today, so this is a no-op that activates for free if the prefix grows.)
        system: [{
          type: 'text',
          text:
            'You are an insurance policy analyst. Write a plain-English 2-3 sentence description of the ' +
            'given insurance form for a product manager audience. Be factual, concise, and accurate. ' +
            'Do not invent coverage details not provided in the input.',
          cache_control: CACHE_1H,
        }],
        messages: [{ role: 'user', content: prompt }],
      }, { timeout: 45_000 })
      addUsage(usageAccum, msg.usage)

      const description = (msg.content.find((b) => b.type === 'text')?.text ?? '').trim()
      if (!description) throw new HttpsError('internal', 'AI returned an empty description.')

      // B11: write the description back through the SAME audited envelope the client mutate()
      // uses (entity + auditEvent + version + searchIndex), instead of a bare Admin-SDK set().
      // A `forms` doc is a governed domain entity, so even a derived/cached field change now
      // carries a truthful audit trail ("description generated by <admin> at <time>") and stays
      // in the ⌘K index. Attributed to the real acting EDITOR/ADMIN, not a system actor.
      await auditedMerge({
        path:       `forms/${formKey}`,
        entityType: 'form',
        patch:      { description },
        actor:      { uid: req.auth.uid, name: (req.auth.token.name as string | undefined) ?? req.auth.uid },
      })

      return { description, cached: false }
    } catch (err) {
      ok = false
      throw err
    } finally {
      void recordUsage({ feature: 'describeForm', model: MODEL_FAST, usage: usageAccum, latencyMs: Date.now() - t0, ok })
    }
  },
)
