// duckcreek/serialize.ts — the deterministic serializer: PDM ⇒ Duck Creek-shaped
// manuscript XML, driven entirely by a DuckCreekMapping. There is NO Anthropic call and
// NO randomness in the hot path: element/attribute names come from the mapping, GUID ids
// are derived from each node's refId (duckcreek/guid.ts), and ordering is fixed — so two
// runs on the same PDM are byte-identical. Every coverage / sub-coverage / limit /
// deductible / option / form (with edition + states) / rating step / factor table / rule
// is represented, and every refId + form number is preserved verbatim.
//
// HONESTY: the golden reference is INSTANCE data and the real manuscript-DEFINITION schema is
// proprietary, so this emits a manuscript-SHAPED document that reuses the sample's
// vocabulary (dctSys namespace; coverage/limit/deductible/options/StatCode with the
// Premium quintet; forms via Form/FormNumber/FormsManuScriptID/UseDCTForms; the
// manuScriptID pattern) plus honest extension attributes (refId on every node,
// validValues lists) so the projection is lossless. See docs/DUCKCREEK_MAPPING.md.
import type {
  PdmProduct, PdmCoverage, PdmTerm, PdmEligibleValue, PdmForm, PdmRule,
  PdmRatingProgram, PdmRatingStep, PdmRatingTable, PdmApplicability,
} from '../pdm/types'
import { el, leaf, empty, writeXml, type XmlNode, type XmlAttr } from './xml'
import { deriveId } from './guid'
import {
  DEFAULT_DUCKCREEK_MAPPING, composeManuscriptId, composeManuscriptVersionId,
  type DuckCreekMapping, type DcNodeType,
} from './mapping'

const DEFAULT_COMMENT =
  'Generated by the Product Reinvention Hub PDM→Duck Creek serializer. Deterministic, ' +
  'mapping-driven, manuscript-SHAPED projection — not a proprietary Duck Creek ' +
  'manuscript-definition export. See docs/DUCKCREEK_MAPPING.md.'

export interface SerializeOptions {
  mapping?: DuckCreekMapping
  comment?: string   // pass '' to omit the leading comment
}

/** Serialize one PDM product into Duck Creek-shaped XML. Pure + deterministic. */
export function serializePdmToDuckCreek(product: PdmProduct, options: SerializeOptions = {}): string {
  const mapping = options.mapping ?? DEFAULT_DUCKCREEK_MAPPING
  const root = buildManuscriptTree(product, mapping)
  const comment = options.comment === '' ? undefined : (options.comment ?? DEFAULT_COMMENT)
  return writeXml(root, comment ? { comment } : {})
}

/** Build the manuscript node tree (exposed for callers who want to post-process before
 *  writing, and reused by the validator so it checks the exact tree that gets written). */
export function buildManuscriptTree(product: PdmProduct, mapping: DuckCreekMapping): XmlNode {
  const E = mapping.elements
  const A = mapping.attrs
  const lineCode = product.line.code
  const bool = (b: boolean): string => (b ? mapping.boolTrue : mapping.boolFalse)
  const id = (type: DcNodeType, seed: string): string => deriveId(mapping.idPrefix[type], `${type}|${seed}`)

  // ── shared: a states + effective-date applicability block ──────────────────
  const statesNode = (app: PdmApplicability): XmlNode => {
    const attrs: XmlAttr[] = [[A.allStates, bool(app.allStates)]]
    if (app.effectiveDate) attrs.push([A.effective, app.effectiveDate])
    const children = app.allStates ? [] : app.states.map(s => leaf(E.state, s))
    return el(E.states, attrs, children)
  }

  // ── typed value list (limit/deductible eligible values) ────────────────────
  const valueNode = (term: PdmTerm, ev: PdmEligibleValue): XmlNode => {
    const attrs: XmlAttr[] = [
      [A.id, id('validValue', `${term.refId}:${ev.id}`)],
      [A.label, ev.label],
      [A.valueType, ev.valueType],
      [A.default, bool(ev.isDefault)],
      [A.enabled, bool(ev.enabled)],
      [A.allStates, bool(ev.applicability.allStates)],
    ]
    if (!ev.applicability.allStates && ev.applicability.states.length) {
      attrs.push([A.stateList, ev.applicability.states.join('|')])
    }
    if (ev.constraintNote) attrs.push([A.notes, ev.constraintNote])
    // SPLIT values carry no scalar; expose the parts as the text (e.g. "100000/300000").
    const text = ev.value !== null ? String(ev.value) : (ev.parts ?? []).join('/')
    return leaf(E.value, text, attrs)
  }

  // ── a limit or deductible typed field ──────────────────────────────────────
  const termFieldNode = (term: PdmTerm): XmlNode => {
    const isDed = term.kind === 'DEDUCTIBLE'
    const attrs: XmlAttr[] = [
      [A.id, id(isDed ? 'deductible' : 'limit', term.refId)],
      [A.t, term.termKey],
      [A.refId, term.refId],
      [A.key, term.key],
      [A.default, String(term.defaultValue)],
      [A.structure, term.structure],
      [A.basis, term.basis],
    ]
    if (term.unit) attrs.push([A.unit, term.unit])
    if (term.ldTableRef) attrs.push([A.ldRef, term.ldTableRef])
    if (term.constraintNote) attrs.push([A.notes, term.constraintNote])
    const children = term.eligibleValues.length
      ? [el(E.validValues, [], term.eligibleValues.map(ev => valueNode(term, ev)))]
      : []
    return el(isDed ? E.deductible : E.limit, attrs, children)
  }

  // ── an OPTION term → a Duck Creek <options> node linked to its coverage ─────
  const optionNode = (coverageId: string, term: PdmTerm): XmlNode => {
    const attrs: XmlAttr[] = [
      [A.id, id('option', term.refId)],
      [A.t, term.termKey],
      [A.refId, term.refId],
      [A.key, term.key],
      [A.cid, coverageId],
      [A.caption, term.label],
      [A.isValid, bool(true)],
      [A.isMandatory, bool(false)],
      [A.isSelected, bool(false)],
      [A.default, String(term.defaultValue)],
    ]
    if (term.notes) attrs.push([A.notes, term.notes])
    return empty(E.options, attrs)
  }

  // ── a coverage (recursively nesting sub-coverages) ─────────────────────────
  const coverageNode = (cov: PdmCoverage): XmlNode => {
    const cid = id('coverage', cov.refId)
    const attrs: XmlAttr[] = [
      [A.id, cid],
      [A.t, cov.termKey],
      [A.refId, cov.refId],
      [A.ind, bool(cov.requirement === 'MANDATORY')],
      [A.req, cov.requirement],
      [A.order, String(cov.order)],
      [A.source, cov.source],
      [A.premiumGenerating, bool(cov.premiumGenerating)],
    ]
    if (cov.applicability.effectiveDate) attrs.push([A.effective, cov.applicability.effectiveDate])

    const children: XmlNode[] = [
      leaf(E.caption, cov.name),
      leaf(E.section, cov.section),
      empty(E.statCode, [[A.id, id('statCode', `${cov.refId}:stat`)]]),
    ]
    for (const fn of cov.formNumbers) children.push(leaf(E.formNumber, fn))
    children.push(statesNode(cov.applicability))
    for (const term of cov.terms) {
      children.push(term.kind === 'OPTION' ? optionNode(cid, term) : termFieldNode(term))
    }
    // A manuscript definition carries no computed premium — emit the quintet as zeros
    // so the shape mirrors the sample without fabricating amounts.
    for (const p of mapping.premiumChildren) children.push(leaf(p, mapping.premiumZero))
    for (const child of cov.children) children.push(coverageNode(child))
    return el(E.coverage, attrs, children)
  }

  // ── a form (with its editions + state/effective applicability) ─────────────
  const formNode = (form: PdmForm): XmlNode => {
    const attrs: XmlAttr[] = [
      [A.id, id('form', form.refId)],
      [A.refId, form.refId],
      [A.category, form.category],
      [A.source, form.source],
      [A.admitted, bool(form.admitted)],
      [A.mandatoryDefault, bool(form.mandatoryDefault)],
      [A.attach, form.attachmentCondition],
      [A.dynamic, bool(form.dynamic)],
    ]
    const editions = el(E.editions, [], form.editions.map(ed =>
      el(E.edition, [
        [A.id, id('edition', `${form.refId}:${ed.edition}`)],
        [A.editionValue, ed.edition],
      ], [statesNode(ed.applicability)])))
    const fields = el(E.fields, [], form.dynamicFields.map(f => {
      const fAttrs: XmlAttr[] = [
        [A.id, id('dynamicField', `${form.refId}:${f.name}`)],
        [A.name, f.name],
        [A.dataType, f.dataType],
        [A.repeating, bool(f.repeating)],
      ]
      if (f.notes) fAttrs.push([A.notes, f.notes])
      const opts = (f.options ?? []).map(o => leaf(E.fieldOption, o))
      return el(E.field, fAttrs, opts)
    }))
    const children: XmlNode[] = [
      leaf(E.formName, form.name),
      leaf(E.formNumber, form.formNumber),
      leaf(E.formsManuScriptID, composeManuscriptId(mapping, lineCode, 'forms')),
      leaf(E.useDctForms, mapping.boolTrue),
      editions,
      statesNode(form.applicability),
      ...form.coverageParts.map(cp => leaf(E.coveragePart, cp)),
      leaf(E.description, form.description),
      fields,
    ]
    return el(E.form, attrs, children)
  }

  // ── rating: a program's ordered steps ──────────────────────────────────────
  const stepNode = (step: PdmRatingStep): XmlNode => {
    const attrs: XmlAttr[] = [
      [A.id, id('ratingStep', step.refId)],
      [A.refId, step.refId],
      [A.key, step.key],
      [A.order, String(step.order)],
      [A.op, step.op],
      [A.label, step.label],
      [A.sourceType, step.sourceType],
    ]
    if (step.tableRef) attrs.push([A.tableRef, step.tableRef])
    if (step.inputKeys && step.inputKeys.length) attrs.push([A.inputKeys, step.inputKeys.join('|')])
    if (step.constValue !== undefined) attrs.push([A.constValue, String(step.constValue)])
    if (step.condition) attrs.push([A.condition, step.condition])
    if (step.roundTo !== undefined) attrs.push([A.roundTo, String(step.roundTo)])
    return empty(E.step, attrs)
  }

  const programNode = (program: PdmRatingProgram): XmlNode =>
    el(E.program, [
      [A.id, id('ratingProgram', program.refId)],
      [A.refId, program.refId],
      [A.name, program.name],
      [A.minimumPremium, String(program.minimumPremium)],
    ], [statesNode(program.applicability), ...program.steps.map(stepNode)])

  // ── rating: a factor / rate table ──────────────────────────────────────────
  const tableNode = (table: PdmRatingTable): XmlNode => {
    const attrs: XmlAttr[] = [
      [A.id, id('factorTable', table.refId)],
      [A.refId, table.refId],
      [A.name, table.name],
      [A.kind, table.kind],
    ]
    if (table.valueColumn) attrs.push([A.valueColumn, table.valueColumn])
    if (table.defaultValue !== undefined) attrs.push([A.defaultValue, String(table.defaultValue)])

    const columns = el(E.columns, [], table.columns.map(c => leaf(E.column, c)))
    const dims = table.dimensions.length
      ? [el(E.dimensions, [], table.dimensions.map(d =>
          el(E.dimension, [
            [A.id, id('tableDimension', `${table.refId}:${d.key}`)],
            [A.key, d.key],
            [A.label, d.label],
          ], d.values.map(v => leaf(E.dimValue, v)))))]
      : []
    const rows = el(E.rows, [], table.rows.map((r, idx) =>
      el(E.row, [[A.id, id('tableRow', `${table.refId}:row:${idx}`)]],
        table.columns.map(col => {
          const v = r[col]
          return leaf(E.cell, v === null || v === undefined ? '' : String(v), [[A.col, col]])
        }))))
    return el(E.table, attrs, [columns, ...dims, rows])
  }

  // ── rules (product rules + form-attach rules) as IF/THEN ────────────────────
  const ruleNode = (rule: PdmRule): XmlNode => {
    const attrs: XmlAttr[] = [
      [A.id, id('rule', rule.refId)],
      [A.refId, rule.refId],
      [A.ruleType, rule.ruleType],
      [A.category, rule.category],
    ]
    if (rule.subCategory) attrs.push([A.subCategory, rule.subCategory])
    if (rule.mandatory !== undefined) attrs.push([A.mandatory, bool(rule.mandatory)])
    const children: XmlNode[] = [
      leaf(E.ifEl, rule.condition),
      el(E.thenEl, [], rule.actions.map(a => leaf(E.action, a))),
      ...rule.coverageRefIds.map(cr => leaf(E.coverageRef, cr)),
      ...rule.formNumbers.map(fn => leaf(E.formNumber, fn)),
      ...(rule.ldTableRef ? [leaf(E.ldTableRef, rule.ldTableRef)] : []),
      statesNode(rule.applicability),
    ]
    return el(E.rule, attrs, children)
  }

  // ── assemble the tree ──────────────────────────────────────────────────────
  const riskNode = el(E.risk, [[A.id, id('risk', `${product.refId}:risk`)]], [
    leaf(E.exposure, mapping.manuscript.lobTokens[lineCode] ?? lineCode, [
      [A.id, id('exposure', `${product.refId}:policyform`)],
      [A.t, mapping.policyFormExposureKey],
    ]),
    ...product.coverages.map(coverageNode),
  ])

  const lineNode = el(E.line, [
    [A.id, id('line', product.line.refId)],
    [A.refId, product.line.refId],
    [A.description, product.line.compactName],
  ], [leaf(E.type, product.line.compactName), riskNode])

  const productNode = el(E.product, [
    [A.id, id('product', product.refId)],
    [A.refId, product.refId],
    [A.t, product.line.compactName],
  ], [
    leaf(E.caption, product.name),
    leaf(E.description, product.description),
    leaf(E.marketSegment, product.marketSegment),
    leaf(E.type, product.line.compactName),
    statesNode(product.applicability),
    lineNode,
  ])

  const formsNode = el(E.forms, [], product.forms.map(formNode))

  const ratingNode = el(E.rating, [], [
    leaf(E.ratingManuScriptID, composeManuscriptId(mapping, lineCode, 'rating')),
    leaf(E.tableManuScriptID, composeManuscriptId(mapping, lineCode, 'tables')),
    ...product.ratingPrograms.map(programNode),
    el(E.factorTables, [], product.ratingTables.map(tableNode)),
  ])

  const rulesNode = el(E.rules, [], product.rules.map(ruleNode))

  const manuscriptRefs = el(E.manuscriptRefs, [[A.id, id('manuscript', `${product.refId}:admin`)]], [
    leaf(E.policyManuScriptID, composeManuscriptId(mapping, lineCode, 'viewModel')),
    leaf(E.policyManuScriptVersionID, composeManuscriptVersionId(mapping, lineCode, 'viewModel')),
    leaf(E.formsManuScriptID, composeManuscriptId(mapping, lineCode, 'forms')),
    leaf(E.ratingManuScriptID, composeManuscriptId(mapping, lineCode, 'rating')),
    leaf(E.tableManuScriptID, composeManuscriptId(mapping, lineCode, 'tables')),
    leaf(E.communicationsManuScriptID, mapping.manuscript.layers.communications),
    leaf(E.useDctForms, mapping.boolTrue),
    leaf(E.useDctFormsAndMessages, mapping.boolTrue),
  ])

  const rootAttrs: XmlAttr[] = []
  if (mapping.namespace.declareOnRoot) {
    rootAttrs.push([`xmlns:${mapping.namespace.prefix}`, mapping.namespace.uri])
  }
  rootAttrs.push(
    [A.manuScriptID, composeManuscriptId(mapping, lineCode, 'viewModel')],
    [A.engineVersion, mapping.manuscript.engineVersion],
    [A.cultureCode, mapping.manuscript.cultureCode],
    [A.currencyCode, mapping.manuscript.currencyCode],
  )

  return el(E.manuscript, rootAttrs, [productNode, formsNode, ratingNode, rulesNode, manuscriptRefs])
}
