// serff/reviewer.ts — Texas DOI redline reviewer lens.
//
// Simulates the checklist a TDI filing examiner runs against a SERFF bundle before
// accepting a homeowners rate/form filing under the file-and-use regime (Chapter 2251).
// Every check cites its source; every known gap is documented so callers understand
// what the automated lens CANNOT catch (a human examiner would still reject bundles
// that fail the gaps listed in `knownGaps`).
//
// Sources:
//   Texas Insurance Code Chapter 2251 — file-and-use framework
//   28 Tex. Admin. Code §5.9327       — marked copies requirement
//   28 Tex. Admin. Code §5.9334       — filing memorandum requirement
//   28 Tex. Admin. Code §5.9334(d)    — rate indication & relativity analysis
//   SERFF Filings Made Easy guide (TDI edition) — tab/grouping structure
//
// Pure TypeScript; zero platform imports.

import type { SerffBundle, ReviewerResult, ReviewerCheckItem, ReviewerFinding } from './types'

// ─── Known gaps — what the lens cannot detect ─────────────────────────────────────
//
// These are documented limitations of the automated check. A bundle that PASSES
// all automated checks can still be rejected by a human examiner for any of these.

const KNOWN_GAPS: string[] = [
  'Actuarial certification: The lens does not verify that a licensed P&C actuary signed ' +
    'the rate indication. TDI may require an actuarial opinion for significant rate changes ' +
    '(28 TAC §5.9334(d)). The bundle must include an actuarial memo if requested.',

  'Comparison to TDI-filed version: Redlines generated by this system compare the clone ' +
    'to its immediate parent product in this platform. TDI examiners compare to the LAST ' +
    'APPROVED VERSION in the SERFF system, which may differ from the parent product here. ' +
    'Verify that the marked copies accurately reflect changes from the TDI-approved base.',

  'Overall impact percentage validation: The lens checks that an overall rate impact is ' +
    'stated but does not validate that the percentage is actuarially supported or that ' +
    'the relativity analysis methodology is technically adequate (28 TAC §5.9334(d)).',

  'Effective date compliance: Texas §2251.101 requires the filing to be received by TDI ' +
    'before the effective date of the change. The lens does not verify this timing constraint.',

  'Coverage amount reasonableness: TDI may reject rates that are significantly outside ' +
    'approved bands for the line of business. The lens checks structure, not rate adequacy.',

  'Mandatory endorsement compliance: If the filing removes a form that is mandatory under ' +
    'a TDI rule or prior order, TDI would flag that. The lens does not track mandatory ' +
    'endorsement obligations.',

  'SERFF filing type / company licensure: The lens does not verify that the filing company ' +
    'is licensed in Texas for the line of business being filed.',
]

// ─── Check runner ─────────────────────────────────────────────────────────────────

type CheckFn = (bundle: SerffBundle) => Omit<ReviewerCheckItem, 'id' | 'label' | 'citation'>

interface CheckDef {
  id:       string
  label:    string
  citation: string
  tab:      SerffBundle['documents'][number]['tabName']
  fn:       CheckFn
}

const CHECKS: CheckDef[] = [
  // ── Check 1: Supporting Documentation tab exists ─────────────────────────────
  {
    id:       'TX-01',
    label:    'Supporting Documentation tab present',
    citation: 'SERFF Filings Made Easy guide (TDI edition) — required tab',
    tab:      'SupportingDocumentation',
    fn: (b) => {
      const hasDocs = b.documents.some(d => d.tabName === 'SupportingDocumentation')
      return {
        passed:  hasDocs,
        tab:     'SupportingDocumentation',
        finding: hasDocs ? undefined : {
          message:  'The Supporting Documentation tab contains no documents.',
          citation: 'SERFF Filings Made Easy guide (TDI edition)',
          severity: 'error',
          tab:      'SupportingDocumentation',
        },
      }
    },
  },

  // ── Check 2: Marked copies present under Supporting Documentation ─────────────
  {
    id:       'TX-02',
    label:    'Marked (redline) copies present in Supporting Documentation',
    citation: '28 Tex. Admin. Code §5.9327 — marked copies required',
    tab:      'SupportingDocumentation',
    fn: (b) => {
      const hasRedlines = b.documents.some(
        d => d.tabName === 'SupportingDocumentation' && d.grouping === 'MarkedCopies' && d.documentType === 'redline',
      )
      const hasChanges = b.changeSet.summary.coveragesAdded + b.changeSet.summary.coveragesRemoved +
        b.changeSet.summary.coveragesModified + b.changeSet.summary.rateTableCellsChanged +
        b.changeSet.summary.ldTableChanges + b.changeSet.summary.formEditionChanges > 0
      const passed = !hasChanges || hasRedlines
      return {
        passed,
        tab:     'SupportingDocumentation',
        finding: passed ? undefined : {
          message:  'Changes were made but no marked (redline) copies are present under Supporting Documentation → Marked Copies.',
          citation: '28 Tex. Admin. Code §5.9327',
          severity: 'error',
          tab:      'SupportingDocumentation',
        },
      }
    },
  },

  // ── Check 3: Each changed form has a marked copy ──────────────────────────────
  {
    id:       'TX-03',
    label:    'Each changed form has a corresponding marked copy',
    citation: '28 Tex. Admin. Code §5.9327(b) — one marked copy per changed form',
    tab:      'SupportingDocumentation',
    fn: (b) => {
      const changedForms = b.changeSet.formEditionChanges.map(fe => fe.formNumber)
      const redlineFormNums = b.documents
        .filter(d => d.tabName === 'SupportingDocumentation' && d.documentType === 'redline' && d.refIds.some(r => changedForms.includes(r)))
        .flatMap(d => d.refIds)
      const missing = changedForms.filter(fn => !redlineFormNums.includes(fn))
      const passed = missing.length === 0
      return {
        passed,
        tab:     'SupportingDocumentation',
        finding: passed ? undefined : {
          message:  `Changed form(s) missing marked copies: ${missing.join(', ')}. Each changed form must have a redline copy in Supporting Documentation.`,
          citation: '28 Tex. Admin. Code §5.9327(b)',
          severity: 'error',
          tab:      'SupportingDocumentation',
          refId:    missing[0],
        },
      }
    },
  },

  // ── Check 4: Filing memorandum present ───────────────────────────────────────
  {
    id:       'TX-04',
    label:    'Filing memorandum present in Supporting Documentation',
    citation: '28 Tex. Admin. Code §5.9334 — explanation-of-changes memo required',
    tab:      'SupportingDocumentation',
    fn: (b) => {
      const hasMemo = b.documents.some(
        d => d.tabName === 'SupportingDocumentation' && d.documentType === 'memo',
      )
      return {
        passed:  hasMemo,
        tab:     'SupportingDocumentation',
        finding: hasMemo ? undefined : {
          message:  'No filing memorandum found under Supporting Documentation. Texas requires an explanation-of-changes memo per 28 TAC §5.9334.',
          citation: '28 Tex. Admin. Code §5.9334',
          severity: 'error',
          tab:      'SupportingDocumentation',
        },
      }
    },
  },

  // ── Check 5: Filing memo includes an overall rate impact statement ───────────
  {
    id:       'TX-05',
    label:    'Filing memorandum includes overall rate impact statement',
    citation: '28 Tex. Admin. Code §5.9334(d) — overall impact percentage required when rates change',
    tab:      'SupportingDocumentation',
    fn: (b) => {
      if (!b.changeSet.summary.hasRateImpact) return { passed: true, tab: 'SupportingDocumentation' }
      const memoDoc = b.documents.find(d => d.tabName === 'SupportingDocumentation' && d.documentType === 'memo')
      if (!memoDoc) return {
        passed:  false,
        tab:     'SupportingDocumentation',
        finding: {
          message:  'Rate changes exist but no memo is present to carry the overall impact statement.',
          citation: '28 Tex. Admin. Code §5.9334(d)',
          severity: 'error',
          tab:      'SupportingDocumentation',
        },
      }
      const memo = typeof memoDoc.content === 'object' && memoDoc.content.kind === 'memo' ? memoDoc.content : null
      const hasImpact = memo !== null && memo.overallImpactPct !== null && memo.overallImpactPct !== undefined
      return {
        passed:  hasImpact,
        tab:     'SupportingDocumentation',
        finding: hasImpact ? undefined : {
          message:  'The filing memorandum does not include an overall rate impact percentage. §5.9334(d) requires this when rates change.',
          citation: '28 Tex. Admin. Code §5.9334(d)',
          severity: 'error',
          tab:      'SupportingDocumentation',
        },
      }
    },
  },

  // ── Check 6: Rate exhibits in Rate/Rule Schedule when rates changed ───────────
  {
    id:       'TX-06',
    label:    'Before-and-after rate exhibits present when rates are changed',
    citation: '28 Tex. Admin. Code §5.9334(d) — rate indication and relativity analysis required',
    tab:      'RateRuleSchedule',
    fn: (b) => {
      if (!b.changeSet.summary.hasRateImpact) return { passed: true, tab: 'RateRuleSchedule' }
      const hasExhibit = b.documents.some(
        d => d.tabName === 'RateRuleSchedule' && d.documentType === 'rateExhibit',
      )
      return {
        passed:  hasExhibit,
        tab:     'RateRuleSchedule',
        finding: hasExhibit ? undefined : {
          message:  'Rate changes exist but no before-and-after rate exhibit is present in the Rate/Rule Schedule tab. §5.9334(d) requires rate indication and relativity analyses.',
          citation: '28 Tex. Admin. Code §5.9334(d)',
          severity: 'error',
          tab:      'RateRuleSchedule',
        },
      }
    },
  },

  // ── Check 7: Form Schedule present when forms changed ─────────────────────────
  {
    id:       'TX-07',
    label:    'Form Schedule (clean forms) present when forms are changed',
    citation: 'SERFF Filings Made Easy guide (TDI edition) — Form Schedule tab required for form filings',
    tab:      'FormSchedule',
    fn: (b) => {
      if (!b.changeSet.summary.hasFormChanges) return { passed: true, tab: 'FormSchedule' }
      const hasCleanForms = b.documents.some(
        d => d.tabName === 'FormSchedule' && d.documentType === 'cleanForm',
      )
      return {
        passed:  hasCleanForms,
        tab:     'FormSchedule',
        finding: hasCleanForms ? undefined : {
          message:  'Form changes exist but no clean (final) copies appear in the Form Schedule tab.',
          citation: 'SERFF Filings Made Easy guide (TDI edition)',
          severity: 'error',
          tab:      'FormSchedule',
        },
      }
    },
  },

  // ── Check 8: General Information tab present ──────────────────────────────────
  {
    id:       'TX-08',
    label:    'General Information tab present',
    citation: 'SERFF Filings Made Easy guide (TDI edition) — required tab',
    tab:      'GeneralInformation',
    fn: (b) => {
      const has = b.documents.some(d => d.tabName === 'GeneralInformation')
      return {
        passed:  has,
        tab:     'GeneralInformation',
        finding: has ? undefined : {
          message:  'General Information tab is missing.',
          citation: 'SERFF Filings Made Easy guide (TDI edition)',
          severity: 'warning',
          tab:      'GeneralInformation',
        },
      }
    },
  },
]

// ─── Public entry point ────────────────────────────────────────────────────────────

/** Run the Texas DOI examiner checklist against a SERFF bundle and return the full
 *  ReviewerResult. `passed` is true only when all 'error'-severity checks pass. */
export function checkTexasBundle(bundle: SerffBundle): ReviewerResult {
  const checklist: ReviewerCheckItem[] = []
  const findings: ReviewerFinding[] = []

  for (const check of CHECKS) {
    const result = check.fn(bundle)
    const item: ReviewerCheckItem = {
      id:       check.id,
      label:    check.label,
      citation: check.citation,
      tab:      check.tab,
      passed:   result.passed,
      finding:  result.finding,
    }
    checklist.push(item)
    if (result.finding) findings.push(result.finding)
  }

  const passed = findings.filter(f => f.severity === 'error').length === 0

  return {
    state:       'TX',
    bundleId:    bundle.filingId,
    checklist,
    findings,
    passed,
    knownGaps:   KNOWN_GAPS,
    generatedAt: new Date().toISOString(),
  }
}
