/**
 * scripts/lib/golden2-schema.mts — the pinned GOLDEN2 contract (CE2).
 *
 * This is the ONE source of truth for the cell-level, dual-family-annotated golden
 * shape. CE3 (pipeline fixes) and CE5 (merge) build against these exact types; the
 * annotate harness writes them; import-eval2 reads them. Pure TypeScript — no I/O,
 * no ExcelJS, no model client — so it can be imported by the vitest locks.
 *
 * Why a NEW golden family (vs tests/golden/import/*.golden.json): the v1 goldens are
 * ENTITY tuples generated by the SAME deterministic parser they grade (the
 * "template-shaped goldens" confession, TEST_MAP section 4 / gap #3). A green v1 board
 * proves parse STABILITY, not that data was not lost. Golden2 records TRUTH at the
 * CELL level — every non-empty cell gets a disposition, every entity a citation, every
 * relationship an edge — so eval2 can prove that a cell present in the source survived
 * into the plan. Dispositions here are deliberately RICHER than any runtime vocabulary;
 * eval2 maps them down (see accountingClassOf).
 */

// ─── Disposition: what a cell TRUTHFULLY is ───────────────────────────────────
// Richer than the runtime's entity/attribute/ignore trichotomy on purpose.
//   ENTITY  a cell that anchors a first-class object (a product/coverage/rule/form/table id or name)
//   ATTR    a cell that is an attribute OF an entity (a limit value, a deductible, a factor, a state)
//   HEADER  a column/section header that structures a table (load-bearing for parsing, not data)
//   SCHEMA  definitions / data-validation / dropdown-authority content (meaning, not instances)
//   LOG     revision/observation/question log content (process history, not product data)
//   NOISE   decoration, blank labels, table-of-contents, contacts, archive copies (requires a noiseRule)
export const DISPOSITIONS = ['ENTITY', 'ATTR', 'NOISE', 'SCHEMA', 'LOG', 'HEADER'] as const
export type Disposition = (typeof DISPOSITIONS)[number]

// ─── Kind: WHICH entity/attribute family a cell belongs to ────────────────────
export const KINDS = [
  'product', 'coverage', 'subCoverage', 'limit', 'deductible', 'form', 'rule',
  'ratingStep', 'table', 'state',
] as const
export type Kind = (typeof KINDS)[number]

// ─── Noise vocabulary (allow-list; extend only with a ledger note) ────────────
// Definitions and Data Validation content is SCHEMA, never NOISE (contract note).
export const NOISE_RULES = [
  'NOISE.TOC', 'NOISE.REVISION_HISTORY', 'NOISE.CONTACTS', 'NOISE.LOG',
  'NOISE.DECORATION', 'NOISE.BLANK_LABEL', 'NOISE.ARCHIVE_SHEET', 'NOISE.DROPDOWN_SRC',
] as const
export type NoiseRule = (typeof NOISE_RULES)[number]

// ─── Edge types (relationships are first-class) ───────────────────────────────
export const EDGE_TYPES = [
  'BELONGS_TO', 'HAS_LIMIT', 'HAS_DEDUCTIBLE', 'ATTACHES_FORM', 'APPLIES_IN_STATE', 'USES_TABLE',
] as const
export type EdgeType = (typeof EDGE_TYPES)[number]

// Mechanism = HOW the edge was established in the source (drives which failures a
// pipeline can excuse): explicit id ref, name match, spatial adjacency, matrix cell.
export const EDGE_MECHANISMS = ['id', 'name', 'spatial', 'matrix'] as const
export type EdgeMechanism = (typeof EDGE_MECHANISMS)[number]

// ─── The record types (match the pinned schema exactly) ───────────────────────

export interface Golden2Cell {
  ref: string                       // "A1"
  disposition: Disposition
  kind: Kind | null
  ofEntity: string | null           // refId (or name) of the entity this cell belongs to
  noiseRule: NoiseRule | null       // REQUIRED iff disposition === 'NOISE'
}

export interface Golden2Entity {
  kind: string                      // one of KINDS (string for forward-compat with CE3 additions)
  refId: string | null
  name: string
  parentRef: string | null
  citations: string[]               // ["SheetName!A1", ...] — at least one, byte-verified
}

export interface Golden2Edge {
  type: EdgeType
  from: string
  to: string
  mechanism: EdgeMechanism
}

export interface Golden2Sheet {
  name: string
  hidden: boolean
  cells: Golden2Cell[]
  entities: Golden2Entity[]
  edges: Golden2Edge[]
}

export interface Golden2Counts {
  products: number
  coverages: number
  forms: number
  distinctFormTokens: number        // deterministic LOWER BOUND (computed from raw cells)
  distinctRefIds: number            // deterministic LOWER BOUND (computed from raw cells)
}

export type AnnotationCoverage = 'full' | 'sampled'

export interface Golden2File {
  file: string
  sha256: string
  annotatedAt: string               // iso8601
  annotators: { a: string; b: string; adjudicator: string }
  sheets: Golden2Sheet[]
  counts: Golden2Counts
  // ── CE2 provenance extensions (additive; ignored by a strict-shape reader) ──
  // Coverage is per-file: 'full' = every substance window annotated; 'sampled' =
  // header + stratified sample annotated, the rest deterministically dispositioned.
  // Recorded so eval2 never treats a sampled file's entity list as exhaustive.
  coverage?: AnnotationCoverage
  sampledWindows?: number
  totalWindows?: number
  // Deterministic lower bounds per kind, computed from raw cells (no model). These
  // are the counting-invariant floor: extracted counts must be >= these, per kind.
  distinctRefIdsByKind?: Record<string, number>
  spendUsd?: number
  agreement?: { windows: number; cellExactRate: number; adjudicated: number; queued: number }
}

// ─── Disposition → runtime accounting class (the map eval2 uses) ──────────────
// The runtime pipeline accounts for a cell as either data it captured (an entity or
// an attribute of one) or content it may legitimately ignore (structure / schema /
// log / noise). SUBSTANCE = the cells whose LOSS is data loss; those are the cells
// eval2's unaccountedCells gate ranges over.
export type AccountingClass = 'entity' | 'attribute' | 'structural' | 'ignorable'

export function accountingClassOf(d: Disposition): AccountingClass {
  switch (d) {
    case 'ENTITY': return 'entity'
    case 'ATTR':   return 'attribute'
    case 'HEADER': return 'structural'
    case 'SCHEMA': return 'structural'
    case 'LOG':    return 'ignorable'
    case 'NOISE':  return 'ignorable'
  }
}

/** SUBSTANCE cells are the ones a lossless pipeline must account for. */
export function isSubstance(d: Disposition): boolean {
  const c = accountingClassOf(d)
  return c === 'entity' || c === 'attribute'
}

// ─── A1 <-> row/col helpers (1-based refs, 0-based indices) ───────────────────
// Shared by cell-enum and the metrics so a golden ref and a census ref agree byte-for-byte.

export function colToNum(col: string): number {
  let n = 0
  for (const ch of col.toUpperCase()) n = n * 26 + (ch.charCodeAt(0) - 64)
  return n
}

export function numToCol(n: number): string {
  let s = ''
  let x = n
  while (x > 0) { const r = (x - 1) % 26; s = String.fromCharCode(65 + r) + s; x = Math.floor((x - 1) / 26) }
  return s
}

const A1_RE = /^([A-Za-z]{1,3})(\d{1,7})$/

/** "B2" -> { row: 1, col: 1 } (0-based). null on a malformed ref. */
export function refToRC(ref: string): { row: number; col: number } | null {
  const m = A1_RE.exec(ref.trim())
  if (!m) return null
  return { row: Number(m[2]) - 1, col: colToNum(m[1]!) - 1 }
}

/** (row0, col0) -> "B2". */
export function rcToRef(row0: number, col0: number): string {
  return `${numToCol(col0 + 1)}${row0 + 1}`
}

/** Split "Sheet!A1" into { sheet, ref }; tolerant of sheet names that contain '!'
 *  by splitting on the LAST '!'. Returns null if there is no '!'. */
export function splitCitation(citation: string): { sheet: string; ref: string } | null {
  const i = citation.lastIndexOf('!')
  if (i < 0) return null
  return { sheet: citation.slice(0, i), ref: citation.slice(i + 1) }
}

// ─── Numeric canonicalization: 1,528 === 1528 === "$1,528.00" ─────────────────
// Used by the annotation reconcile step and by eval2 numeric fidelity so the two
// families agreeing on a value are not split by formatting.
export function canonicalizeNumeric(v: unknown): string | null {
  if (v === null || v === undefined) return null
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : null
  const s = String(v).trim()
  if (s === '') return null
  const numericish = s.replace(/[$,\s%]/g, '')
  if (/^-?\d+(\.\d+)?$/.test(numericish)) return String(Number(numericish))
  return s.toLowerCase().replace(/\s+/g, ' ')
}

// ─── Validators (pure; used by annotate + eval2 + the locks) ──────────────────

export interface ValidationResult { ok: boolean; errors: string[] }

const DISPO_SET = new Set<string>(DISPOSITIONS)
const KIND_SET = new Set<string>(KINDS)
const NOISE_SET = new Set<string>(NOISE_RULES)
const EDGE_SET = new Set<string>(EDGE_TYPES)
const MECH_SET = new Set<string>(EDGE_MECHANISMS)

/** Validate a single annotated cell against the contract. */
export function validateCell(c: Golden2Cell, where: string): string[] {
  const e: string[] = []
  if (typeof c.ref !== 'string' || !A1_RE.test(c.ref)) e.push(`${where}: bad ref "${c.ref}"`)
  if (!DISPO_SET.has(c.disposition)) e.push(`${where}: bad disposition "${c.disposition}"`)
  if (c.kind !== null && !KIND_SET.has(c.kind)) e.push(`${where}: bad kind "${c.kind}"`)
  // NOISE requires a noiseRule from the allow-list; non-NOISE must NOT carry one.
  if (c.disposition === 'NOISE') {
    if (!c.noiseRule || !NOISE_SET.has(c.noiseRule)) e.push(`${where}: NOISE cell needs a valid noiseRule (got "${c.noiseRule}")`)
  } else if (c.noiseRule != null) {
    e.push(`${where}: non-NOISE cell must not carry a noiseRule ("${c.noiseRule}")`)
  }
  return e
}

export function validateEdge(ed: Golden2Edge, where: string): string[] {
  const e: string[] = []
  if (!EDGE_SET.has(ed.type)) e.push(`${where}: bad edge type "${ed.type}"`)
  if (!MECH_SET.has(ed.mechanism)) e.push(`${where}: bad edge mechanism "${ed.mechanism}"`)
  if (!ed.from || !ed.to) e.push(`${where}: edge missing from/to`)
  return e
}

/** Full structural validation of a golden2 file. Does NOT resolve citations against
 *  a workbook (that is the haiku byte-verify swarm's job, and eval2's citationResolve). */
export function validateGolden2File(obj: unknown): ValidationResult {
  const errors: string[] = []
  const f = obj as Partial<Golden2File> | null
  if (!f || typeof f !== 'object') return { ok: false, errors: ['not an object'] }
  if (typeof f.file !== 'string') errors.push('missing file')
  if (typeof f.sha256 !== 'string' || !/^[0-9a-f]{64}$/i.test(f.sha256)) errors.push('missing/invalid sha256')
  if (!Array.isArray(f.sheets)) { errors.push('missing sheets[]'); return { ok: false, errors } }
  for (const sh of f.sheets) {
    const w = `sheet "${sh?.name}"`
    if (typeof sh?.name !== 'string') errors.push(`${w}: missing name`)
    if (typeof sh?.hidden !== 'boolean') errors.push(`${w}: missing hidden`)
    if (!Array.isArray(sh?.cells)) errors.push(`${w}: missing cells[]`)
    else for (const c of sh.cells) errors.push(...validateCell(c, `${w} cell ${c?.ref}`))
    if (!Array.isArray(sh?.entities)) errors.push(`${w}: missing entities[]`)
    else for (const en of sh.entities) {
      if (!Array.isArray(en?.citations) || en.citations.length === 0) errors.push(`${w}: entity "${en?.name}" (${en?.refId}) has no citation — citations-or-discarded`)
    }
    if (!Array.isArray(sh?.edges)) errors.push(`${w}: missing edges[]`)
    else for (const ed of sh.edges) errors.push(...validateEdge(ed, `${w} edge ${ed?.from}->${ed?.to}`))
  }
  const c = f.counts
  if (!c || typeof c.products !== 'number' || typeof c.coverages !== 'number'
    || typeof c.forms !== 'number' || typeof c.distinctFormTokens !== 'number'
    || typeof c.distinctRefIds !== 'number') errors.push('missing/invalid counts{}')
  return { ok: errors.length === 0, errors }
}
