import React, { useEffect, useState } from 'react';
import { listPrompts, suggestPrompt, promptEvents, promptHealth, upsertPrompt, togglePrompt } from './api';
import { Box, Typography, Button, TextField, Dialog, DialogTitle, DialogContent, DialogActions, Chip, CircularProgress, Stack, Alert } from '@mui/material';

const PromptList = ({ prompts, onSelect }) => {
  return (
    <Box sx={{ maxHeight: 260, overflow: 'auto', border: '1px solid #ccc', borderRadius: 2, p:1 }}>
      {prompts.map(p => (
        <Box key={p.id} sx={{ mb:1, p:1, bgcolor: p.enabled ? '#f5faff' : '#fafafa', borderRadius:1, border:'1px solid #ddd', cursor:'pointer' }} onClick={() => onSelect(p)}>
          <Typography variant="subtitle2" sx={{ fontWeight:'bold' }}>{p.id}</Typography>
          <Typography variant="caption" sx={{ display:'block' }}>{p.intent} | personas: {p.personas && p.personas.join(', ')}</Typography>
          <Stack direction="row" spacing={0.5} sx={{ mt:0.5, flexWrap:'wrap' }}>
            {(p.activation_keywords||[]).slice(0,6).map(k => <Chip key={k} size="small" label={k} />)}
          </Stack>
        </Box>
      ))}
    </Box>
  );
};

const SuggestPanel = ({ onSuggestion }) => {
  const [question,setQuestion] = useState('');
  const [persona,setPersona] = useState('developer');
  const [loading,setLoading] = useState(false);
  const [result,setResult] = useState(null);
  const runSuggest = async () => {
    if(!question.trim()) return;
    setLoading(true);
    try { const r = await suggestPrompt(question, persona); setResult(r); onSuggestion && onSuggestion(r); } catch(e) { console.error(e); } finally { setLoading(false); }
  };
  return (
    <Box sx={{ mb:2 }}>
      <Typography variant="subtitle2" sx={{ mb:1 }}>Suggest Catalog Prompt</Typography>
      <Stack direction="row" spacing={1} sx={{ mb:1 }}>
        <TextField label="Persona" size="small" value={persona} onChange={e=>setPersona(e.target.value)} sx={{ width:140 }} />
        <TextField label="Question" size="small" value={question} onChange={e=>setQuestion(e.target.value)} sx={{ flex:1 }} />
        <Button variant="contained" onClick={runSuggest} disabled={loading}>Suggest</Button>
      </Stack>
      {loading && <CircularProgress size={20} />}
      {result && (<Typography variant="caption">Matched: {String(result?.suggestion?.matched)} {result?.suggestion?.prompt_id && ` -> ${result.suggestion.prompt_id}`} (reason={result?.suggestion?.reason || 'ok'})</Typography>)}
    </Box>
  );
};

const PromptDetailModal = ({ open, prompt, onClose, onToggle }) => {
  if(!prompt) return null;
  return (
    <Dialog open={open} onClose={onClose} maxWidth="md" fullWidth>
      <DialogTitle>Prompt: {prompt.id}</DialogTitle>
      <DialogContent dividers>
        <Typography variant="body2" sx={{ whiteSpace:'pre-wrap' }}>{prompt.prompt}</Typography>
        <Typography variant="caption" sx={{ display:'block', mt:1 }}>Intent: {prompt.intent}</Typography>
        <Typography variant="caption" sx={{ display:'block' }}>Personas: {prompt.personas && prompt.personas.join(', ')}</Typography>
        <Typography variant="caption" sx={{ display:'block' }}>Keywords: {(prompt.activation_keywords||[]).join(', ')}</Typography>
        <Typography variant="caption" sx={{ display:'block' }}>Tools: {(prompt.tool_hints||[]).join(', ')}</Typography>
        <Typography variant="caption" sx={{ display:'block' }}>Extractors: {(prompt.param_extractors||[]).join(', ')}</Typography>
        <Chip label={prompt.enabled ? 'Enabled' : 'Disabled'} color={prompt.enabled ? 'success':'default'} size="small" sx={{ mt:1 }} />
      </DialogContent>
      <DialogActions>
        <Button onClick={()=>onToggle && onToggle(prompt)}>{prompt.enabled ? 'Disable':'Enable'}</Button>
        <Button onClick={onClose}>Close</Button>
      </DialogActions>
    </Dialog>
  );
};

const UpsertModal = ({ open, onClose, onSubmit }) => {
  const [id,setId] = useState('');
  const [intent,setIntent] = useState('incident_triage');
  const [personas,setPersonas] = useState('developer');
  const [keywords,setKeywords] = useState('incident, triage, similar, kb, knowledge');
  const [tools,setTools] = useState('fetch_incident_resolution_history, search_similar_incidents');
  const [prompt,setPrompt] = useState('Review similar resolved incidents, summarize resolution (not workaround) details, and highlight knowledge base gaps.');
  const [confidence,setConfidence] = useState('0.4');
  const [saving,setSaving] = useState(false);
  const [error,setError] = useState(null);
  const [autoGenerated,setAutoGenerated] = useState(false);
  const [touchedId,setTouchedId] = useState(false);
  const [summary,setSummary] = useState('');
  const reset = () => { setId(''); setIntent(''); setPersonas('developer'); setKeywords(''); setTools(''); setPrompt(''); setConfidence('0.4'); setError(null); };
  // Auto populate ID when modal opens
  useEffect(()=>{
    if(open){
      if(!id){
        const gen = `custom_${Date.now().toString(36)}`;
        setId(gen);
        setAutoGenerated(true);
      }
    } else {
      reset();
      setAutoGenerated(false);
      setTouchedId(false);
    }
  },[open]);
  // Auto-generate summary based on fields
  useEffect(()=>{
    const personasArr = personas.split(',').map(p=>p.trim()).filter(Boolean);
    const toolsArr = tools.split(',').map(t=>t.trim()).filter(Boolean);
    const kwArr = keywords.split(',').map(k=>k.trim()).filter(Boolean);
    const what = `Intent '${intent}' targeting personas [${personasArr.join(', ')}] with keywords ${kwArr.join(', ')}.`;
    const whyParts = [];
    if(toolsArr.length) whyParts.push(`tools (${toolsArr.join(', ')}) provide incident & knowledge signals`);
    if(kwArr.length) whyParts.push(`keywords guide initial matching and scoring`);
    const why = 'Why: ' + (whyParts.join('; ') || 'standardize triage reasoning');
    const howSteps = [];
    if(kwArr.length) howSteps.push('keyword match');
    if(toolsArr.length) howSteps.push('tool execution');
    const how = 'How: ' + (howSteps.join(' -> ') || 'direct prompt injection');
    setSummary(`${what} ${why} ${how}`);
  },[intent, personas, tools, keywords]);
  // If intent changes and ID was auto-generated and not manually touched, derive slugged id
  useEffect(()=>{
    if(autoGenerated && !touchedId && intent.trim()){
      const slugBase = intent.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'').slice(0,40);
      const composed = `${slugBase || 'prompt'}_${Date.now().toString(36)}`;
      setId(composed);
    }
  },[intent, autoGenerated, touchedId]);
  const handleSubmit = async () => {
    setError(null);
    if(!id.trim()||!intent.trim()||!prompt.trim()) { setError('id, intent, prompt required'); return; }
    const entry = {
      id: id.trim(),
      intent: intent.trim(),
      personas: personas.split(',').map(p=>p.trim()).filter(Boolean),
      activation_keywords: keywords.split(',').map(k=>k.trim()).filter(Boolean),
      tool_hints: tools.split(',').map(t=>t.trim()).filter(Boolean),
      prompt: prompt.trim(),
      enabled: true,
      status: 'active',
      version: 1,
      description: '',
      param_extractors: [],
      expected_receipt: '',
      metadata: { confidence_threshold: parseFloat(confidence) || 0.4 }
    };
    entry.summary = summary.slice(0, 800);
    setSaving(true);
    try { await onSubmit(entry); reset(); onClose(); } catch(e){
      console.error(e);
      const detail = e?.response?.data?.detail || e?.response?.data?.error || e?.message;
      setError(detail || 'upsert failed');
    } finally { setSaving(false); }
  };
  return (
    <Dialog open={open} onClose={onClose} maxWidth="md" fullWidth>
      <DialogTitle>Upsert Prompt Entry</DialogTitle>
      <DialogContent dividers>
        {error && <Alert severity="error" sx={{ mb:1 }}>{error}</Alert>}
        <Stack spacing={1}>
          <TextField label="ID" size="small" value={id} onChange={e=>{ setId(e.target.value); setTouchedId(true); }} helperText={autoGenerated && !touchedId ? 'Auto‑generated; will adapt to intent until you edit' : 'Unique identifier'} />
          <TextField label="Intent" size="small" value={intent} onChange={e=>setIntent(e.target.value)} />
          <TextField label="Personas (comma)" size="small" value={personas} onChange={e=>setPersonas(e.target.value)} />
          <TextField label="Activation Keywords (comma)" size="small" value={keywords} onChange={e=>setKeywords(e.target.value)} />
          <TextField label="Tool Hints (comma)" size="small" value={tools} onChange={e=>setTools(e.target.value)} />
          <TextField label="Confidence Threshold" size="small" value={confidence} onChange={e=>setConfidence(e.target.value)} />
          <TextField label="Prompt Text" size="small" multiline minRows={4} value={prompt} onChange={e=>setPrompt(e.target.value)} />
          <TextField label="Summary (what/why/how)" size="small" multiline minRows={3} value={summary} onChange={e=>setSummary(e.target.value)} />
          <Typography variant="caption" color="text.secondary">Fields: id,intent,personas,keywords,tools,prompt,confidence. Others defaulted.</Typography>
        </Stack>
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose} disabled={saving}>Cancel</Button>
        <Button variant="contained" onClick={handleSubmit} disabled={saving}>{saving?'Saving...':'Save'}</Button>
      </DialogActions>
    </Dialog>
  );
};

const PromptManagerPage = ({ userPersona='developer' }) => {
  const [prompts,setPrompts] = useState([]);
  const [activeOnly,setActiveOnly] = useState(true);
  const [personaFilter,setPersonaFilter] = useState(userPersona || 'developer');
  const [loading,setLoading] = useState(false);
  const [selected,setSelected] = useState(null);
  const [events,setEvents] = useState([]);
  const [health,setHealth] = useState(null);
  const [showUpsert,setShowUpsert] = useState(false);
  const [saving,setSaving] = useState(false);

  const load = async () => {
    setLoading(true);
    try {
      const list = await listPrompts(personaFilter || null, activeOnly);
      // Preserve selection reference to avoid modal flicker
      const previousSelectedId = selected?.id;
      setPrompts(list.prompts || []);
      if (previousSelectedId) {
        const updated = (list.prompts||[]).find(p=>p.id===previousSelectedId);
        if (updated) setSelected(updated); // refresh but keep modal stable
      }
      const ev = await promptEvents(null, 25);
      setEvents(ev.events || []);
      const h = await promptHealth();
      setHealth(h.health || h);
    } catch(e) { console.error(e); } finally { setLoading(false); }
  };
  // Debounce load triggers to reduce layout thrash
  useEffect(()=>{
    const t = setTimeout(()=>{ if(!selected) load(); }, 180);
    return ()=>clearTimeout(t);
  },[activeOnly, personaFilter, selected]);

  // Update filter if userPersona prop changes and field untouched
  useEffect(()=>{
    if(!personaFilter && userPersona){
      setPersonaFilter(userPersona);
    }
  },[userPersona]);

  const handleToggle = async (p) => {
    try {
      await togglePrompt(p.id, !p.enabled);
      load();
    } catch(e) { console.error(e); }
  };

  const handleUpsertSubmit = async (entry) => {
    setSaving(true);
    try { await upsertPrompt(entry); await load(); } finally { setSaving(false); }
  };

  return (
    <Box sx={{ maxWidth:900, margin:'0 auto', border:'1px solid #d0d0d0', borderRadius:2, padding:2, background:'#ffffff', boxShadow:'0 2px 6px rgba(0,0,0,0.06)', minHeight: '520px' }}>
      <Typography variant="h6" sx={{ mb:2, fontWeight:'bold' }}>Prompt Manager</Typography>
      <Stack direction="row" spacing={1} sx={{ mb:2, flexWrap:'wrap' }}>
        <TextField label="Persona Filter" size="small" value={personaFilter} onChange={e=>setPersonaFilter(e.target.value)} />
        <Button variant="outlined" onClick={()=>setActiveOnly(a=>!a)}>Active: {String(activeOnly)}</Button>
        <Button variant="contained" onClick={load} disabled={loading}>Refresh</Button>
        <Button variant="contained" color="secondary" onClick={()=>setShowUpsert(true)} disabled={saving}>New Prompt</Button>
        <Button size="small" variant="text" onClick={()=>setPersonaFilter(userPersona || 'developer')}>Mine</Button>
        <Button size="small" variant="text" onClick={()=>setPersonaFilter('')}>All</Button>
      </Stack>
      <SuggestPanel />
      {loading && <CircularProgress size={24} />}
      <Box sx={{ border:'1px solid #ececec', borderRadius:2, p:1, mb:2, background:'#fafafa', minHeight:230 }}>
        <PromptList prompts={prompts} onSelect={p=>setSelected(p)} />
      </Box>
      <Box sx={{ mt:2 }}>
        <Typography variant="subtitle2">Recent Prompt Events</Typography>
        <Box sx={{ maxHeight:140, overflow:'auto', border:'1px solid #ddd', p:1, borderRadius:1, background:'#fcfcfc' }}>
          {events.map(ev => (
            <Typography key={ev.ts} variant="caption" sx={{ display:'block' }}>{new Date(ev.ts*1000).toLocaleTimeString()} - {ev.type} {ev.prompt_id && `(${ev.prompt_id})`} {ev.reason && `reason=${ev.reason}`}</Typography>
          ))}
        </Box>
      </Box>
      <Box sx={{ mt:2 }}>
        <Typography variant="subtitle2" sx={{ fontWeight:'bold' }}>Health</Typography>
        {health && (
          <Typography variant="caption">Prompts: {health.prompt_count} Active: {health.active_count}</Typography>
        )}
      </Box>
      <PromptDetailModal open={!!selected} prompt={selected} onClose={()=>setSelected(null)} onToggle={handleToggle} />
      <UpsertModal open={showUpsert} onClose={()=>setShowUpsert(false)} onSubmit={handleUpsertSubmit} />
    </Box>
  );
};

export default PromptManagerPage;
