'use strict'
// data.js — /api/db/* : TENANT-ISOLATED Cosmos data layer.
//
// Every read and write is scoped to req.user.tenantId (derived server-side from
// the JWT — the client cannot choose another tenant). Isolation is enforced two
// ways: (1) the partition key is `${tenantId}|${base}` so a tenant's docs live in
// tenant-specific physical partitions, and (2) every query filters c.tenantId.
// The atomic mutate() envelope (entity + audit + version + searchIndex) still
// commits in ONE transactional batch — all four share the tenant partition.
//
// Role matrix: reads = any authed (VIEWER+); writes = EDITOR+; AI = ANALYST+ (ai.js).

const express = require('express')
const crypto = require('crypto')
const { docs } = require('./cosmos')
const { requireAuth, requireRole, requireTenant } = require('./auth')

const router = express.Router()
const MAX_LIST = 1000
const BATCH_OPS = 96

const segs = (p) => String(p || '').split('/').filter(Boolean)
const baseKey = (path) => { const s = segs(path); return (s[0] === 'products' && s[1]) ? s[1] : (s[0] || 'root') }
const pkFor = (tid, path) => `${tid}|${baseKey(path)}`
const collOf = (path) => segs(path).slice(0, -1).join('/')
const idFor = (prefix, key) => `${prefix}:${String(key).replace(/[/\\?#]/g, '~')}`
const auditId = () => `aud:${Date.now().toString(36)}-${crypto.randomUUID()}`
const searchText = (data) => Object.values(data || {}).filter((v) => typeof v === 'string').join(' ').slice(0, 4000)
const fieldDiff = (prev, next) => {
  const before = {}; const changed = {}
  const keys = new Set([...Object.keys(prev || {}), ...Object.keys(next || {})])
  for (const k of keys) {
    if (JSON.stringify((prev || {})[k]) !== JSON.stringify((next || {})[k])) { before[k] = (prev || {})[k]; changed[k] = (next || {})[k] }
  }
  return { before, changed }
}

async function readEntity(tid, path) {
  try {
    const r = (await docs.item(idFor('ent', path), pkFor(tid, path)).read()).resource
    return r && r.tenantId === tid ? r : null // defense-in-depth
  } catch { return null }
}

// ─── reads (any authenticated role, tenant-scoped) ───────────────────────────
router.get('/get', requireAuth, requireTenant, async (req, res) => {
  const ent = await readEntity(req.user.tenantId, req.query.path)
  // Inject the entity's natural id (last path segment) so the client has a stable identifier.
  const id = ent ? segs(ent.path).at(-1) : null
  res.json({ data: ent ? { id, ...ent.data } : null })
})

router.post('/list', requireAuth, requireTenant, async (req, res) => {
  const { path, query } = req.body || {}
  const params = [{ name: '@coll', value: String(path || '') }, { name: '@tid', value: req.user.tenantId }]
  let where = "c.kind = 'entity' AND c.coll = @coll AND c.tenantId = @tid"
  const opMap = { '==': '=', '!=': '!=', '<': '<', '<=': '<=', '>': '>', '>=': '>=' }
  ;(query?.where || []).forEach((w, i) => {
    const p = `@w${i}`; params.push({ name: p, value: w.value })
    where += w.op === 'array-contains' ? ` AND ARRAY_CONTAINS(c.data.${w.field}, ${p})` : ` AND c.data.${w.field} ${opMap[w.op] || '='} ${p}`
  })
  const limit = Math.min(query?.limit || MAX_LIST, MAX_LIST)
  // SELECT TOP caps Cosmos server-side so fetchAll() never loads more than limit rows into heap.
  let sql = `SELECT TOP ${limit} c.data, c.path FROM c WHERE ${where}`
  ;(query?.orderBy || []).forEach((o, i) => { sql += `${i === 0 ? ' ORDER BY' : ','} c.data.${o.field} ${(o.dir || 'asc').toUpperCase()}` })
  const { resources } = await docs.items.query({ query: sql, parameters: params }, { maxItemCount: limit }).fetchAll()
  res.json({ data: resources.map((r) => ({ id: segs(r.path).at(-1), ...r.data })) })
})

// ─── grounding-chunk hook ────────────────────────────────────────────────────
// chunk-shared.cjs is generated by `pnpm build:chunk` (esbuild bundle of
// shared/src/retrieval/chunk.ts). Loaded lazily so the server starts even if
// the bundle is absent (e.g. a fresh clone before `pnpm build`).
let _chunker = null
function getChunker() {
  if (!_chunker) { try { _chunker = require('./chunk-shared.cjs') } catch { _chunker = {} } }
  return _chunker
}

// Build a groundingChunk Cosmos op for the entity being written, or return null
// if the entity type is not chunkable or the chunker is unavailable.
function buildChunkOp(entityType, path, data, pk, tid, now) {
  try {
    const ch = getChunker()
    const s = segs(path)
    const pid = s[0] === 'products' && s[1] ? s[1] : null
    const refId = data.refId || s.at(-1) || ''
    let chunk = null
    if (entityType === 'product') chunk = ch.chunkProduct?.(data)
    else if (entityType === 'coverage' && pid) chunk = ch.chunkCoverage?.(data, pid)
    else if (entityType === 'rule' && pid) chunk = ch.chunkRule?.(data, pid)
    else if (entityType === 'formRule' && pid) chunk = ch.chunkFormRule?.(data, pid)
    else if (entityType === 'ratingProgram' && pid) chunk = ch.chunkRatingProgram?.(data, pid)
    else if (entityType === 'ldTable') chunk = ch.chunkLdTable?.(refId, data)
    else if (entityType === 'rtTable') chunk = ch.chunkRtTable?.(refId, data)
    else if (entityType === 'form') chunk = ch.chunkForm?.(data)
    else if (entityType === 'dictionary') chunk = ch.chunkDictionary?.(data)
    if (!chunk?.id || !chunk?.text) return null
    return {
      operationType: 'Upsert',
      resourceBody: {
        id: idFor('chunk', path), pk, tenantId: tid,
        kind: 'entity', coll: 'groundingChunks',
        entityPath: path, entityType,
        data: { id: chunk.id, text: chunk.text, contentHash: chunk.contentHash, metadata: chunk.metadata, type: entityType, productId: chunk.metadata?.productId || null, updatedAt: now },
        updatedAt: now,
      },
    }
  } catch { return null }
}

// ─── mutations (EDITOR+, tenant-scoped, atomic) ──────────────────────────────
function envelope(tid, payload, actor) {
  const { op, path, data = {}, entityType } = payload
  const pk = pkFor(tid, path)
  const now = new Date().toISOString()
  return async () => {
    const current = await readEntity(tid, path)
    const curRev = current?.rev ?? 0
    if (payload.expectedRev !== undefined && curRev !== payload.expectedRev) { const e = new Error('conflict'); e.code = 'CONFLICT'; throw e }
    // parentId validation: must resolve to an existing same-tenant entity (DEF-0003)
    if (data.parentId && op !== 'delete') {
      const s = segs(path)
      const parentPath = [...s.slice(0, -1), String(data.parentId)].join('/')
      const parent = await readEntity(tid, parentPath)
      if (!parent) { const e = new Error('invalid_parent'); e.code = 'INVALID_PARENT'; throw e }
    }
    const rev = curRev + 1
    const entityData = { ...data, rev, updatedAt: now, updatedBy: actor }
    const common = { pk, tenantId: tid }
    const ops = []
    if (op === 'delete') ops.push({ operationType: 'Delete', id: idFor('ent', path) })
    else ops.push({ operationType: 'Upsert', resourceBody: { id: idFor('ent', path), ...common, kind: 'entity', path, coll: collOf(path), entityType, rev, data: entityData, updatedAt: now } })
    ops.push({ operationType: 'Create', resourceBody: { id: auditId(), ...common, kind: 'audit', entityPath: path, entityType, op, actor, rev, at: now } })
    ops.push({ operationType: 'Upsert', resourceBody: { id: idFor('ver', `${path}:${rev}`), ...common, kind: 'version', entityPath: path, rev, op, diff: op === 'delete' ? null : fieldDiff(current?.data, data), actor, at: now } })
    ops.push({ operationType: 'Upsert', resourceBody: { id: idFor('idx', path), ...common, kind: 'searchIndex', entityPath: path, entityType, deleted: op === 'delete', text: searchText(data), at: now } })
    // 5th op: grounding chunk (non-delete only; same pk → same Cosmos partition → atomic)
    if (op !== 'delete') {
      const chunkOp = buildChunkOp(entityType, path, data, pk, tid, now)
      if (chunkOp) ops.push(chunkOp)
    }
    return { pk, ops, rev }
  }
}

router.post('/mutate', requireRole('EDITOR'), requireTenant, async (req, res) => {
  const payload = (req.body || {}).payload || req.body
  const actor = { uid: req.user.uid, name: req.user.name }
  try {
    const { pk, ops, rev } = await envelope(req.user.tenantId, payload, actor)()
    const r = await docs.items.batch(ops, pk)
    if (r.result?.some((o) => o.statusCode >= 400)) return res.status(500).json({ error: 'batch_failed', detail: r.result })
    res.json({ ok: true, rev })
  } catch (e) {
    if (e.code === 'CONFLICT') return res.status(409).json({ error: 'conflict' })
    if (e.code === 'INVALID_PARENT') return res.status(422).json({ error: e.message })
    res.status(500).json({ error: 'mutate_failed', detail: String(e.message || e) })
  }
})

router.post('/mutateBatch', requireRole('EDITOR'), requireTenant, async (req, res) => {
  const payloads = (req.body || {}).payloads || []
  const actor = { uid: req.user.uid, name: req.user.name }
  // Track chunk commits so that on failure the caller can identify partial-commit state (DEF-0013).
  let committedChunks = 0; let totalChunks = 0
  try {
    const byPk = new Map()
    for (const p of payloads) { const b = await envelope(req.user.tenantId, p, actor)(); if (!byPk.has(b.pk)) byPk.set(b.pk, []); byPk.get(b.pk).push(b.ops) }
    for (const [pk, opsList] of byPk) {
      let chunk = []
      for (const ops of opsList) {
        if (chunk.length + ops.length > BATCH_OPS) { totalChunks++; await docs.items.batch(chunk, pk); committedChunks++; chunk = [] }
        chunk.push(...ops)
      }
      if (chunk.length) { totalChunks++; await docs.items.batch(chunk, pk); committedChunks++ }
    }
    res.json({ ok: true, count: payloads.length })
  } catch (e) {
    if (e.code === 'CONFLICT') return res.status(409).json({ error: 'conflict' })
    if (e.code === 'INVALID_PARENT') return res.status(422).json({ error: e.message })
    const partial = committedChunks > 0 && committedChunks < totalChunks
    res.status(500).json({ error: partial ? 'batch_partial' : 'batch_failed', committedChunks, totalChunks, detail: String(e.message || e) })
  }
})

router.post('/vote', requireRole('EDITOR'), requireTenant, async (req, res) => {
  const { path } = req.body || {}; const uid = req.user.uid; const tid = req.user.tenantId
  const ent = await readEntity(tid, path)
  if (!ent) return res.status(404).json({ error: 'not_found' })
  const votes = ent.data.votes || { voters: [], count: 0 }
  if (!votes.voters.includes(uid)) { votes.voters = [...votes.voters, uid]; votes.count = (votes.count || 0) + 1 }
  const actor = { uid, name: req.user.name }
  await mutateInternal(tid, { op: 'update', path, data: { ...ent.data, votes }, entityType: ent.entityType }, actor)
  res.json({ ok: true, count: votes.count })
})

router.post('/setNewsPins', requireRole('EDITOR'), requireTenant, async (req, res) => {
  const { uid, pinnedHashes } = req.body || {}; const tid = req.user.tenantId
  if (uid !== req.user.uid) return res.status(403).json({ error: 'forbidden' })
  const path = `newsPrefs/${uid}`
  const actor = { uid: req.user.uid, name: req.user.name }
  await mutateInternal(tid, { op: 'update', path, data: { pinnedHashes: pinnedHashes || [] }, entityType: 'newsPrefs' }, actor)
  res.json({ ok: true })
})

router.post('/presence/join', requireRole('EDITOR'), requireTenant, async (req, res) => {
  const { pid } = req.body || {}; const tid = req.user.tenantId
  const { presence } = require('./cosmos')
  await presence.items.upsert({ id: `${tid}:${pid}:${req.user.uid}`, pid: `${tid}:${pid}`, uid: req.user.uid, name: req.user.name, at: Date.now() })
  res.json({ ok: true })
})
router.post('/presence/watch', requireAuth, requireTenant, async (req, res) => {
  const { pid } = req.body || {}; const tid = req.user.tenantId
  const { presence } = require('./cosmos')
  const { resources } = await presence.items.query({ query: 'SELECT c.uid FROM c WHERE c.pid = @pid', parameters: [{ name: '@pid', value: `${tid}:${pid}` }] }).fetchAll()
  res.json({ viewers: [...new Set(resources.map((r) => r.uid))] })
})

// Internal mutate for same-process callers (e.g., ai.js persistSummary).
async function mutateInternal(tid, payload, actor) {
  const { pk, ops, rev } = await envelope(tid, payload, actor)()
  const r = await docs.items.batch(ops, pk)
  if (r.result?.some((o) => o.statusCode >= 400)) throw new Error('batch_failed')
  return { ok: true, rev }
}

module.exports = Object.assign(router, { mutateInternal })
