'use strict'
// data.js — /api/db/* : TENANT-ISOLATED Cosmos data layer.
//
// Every read and write is scoped to req.user.tenantId (derived server-side from
// the JWT — the client cannot choose another tenant). Isolation is enforced two
// ways: (1) the partition key is `${tenantId}|${base}` so a tenant's docs live in
// tenant-specific physical partitions, and (2) every query filters c.tenantId.
// The atomic mutate() envelope (entity + audit + version + searchIndex + chainHead)
// commits in ONE transactional batch — all ops share the tenant partition. Audit
// events are hash-chained per entityPath (SHA-256 over canonical content + the
// previous event's hash) so the audit trail is tamper-evident; GET /audit/verify
// reconstructs and checks every chain.
//
// Role matrix: reads = any authed (VIEWER+); writes = EDITOR+; AI = ANALYST+ (ai.js).

const express = require('express')
const crypto = require('crypto')
const { resolveTenantStore } = require('./cosmos')
const { requireAuth, requireRole, requireTenant, resolveTenantForPrincipal } = require('./auth')
const { requireCapability } = require('./authz')
// audit-chain-shared.cjs is generated by `pnpm build:audit-chain` (esbuild bundle of
// shared/src/audit/chain.ts) and COMMITTED — a hard require, not a lazy best-effort
// load: tamper evidence on the audit stream is load-bearing, never optional.
const { computeAuditHash, verifyAuditChain } = require('./audit-chain-shared.cjs')
const log = require('./log') // structured NDJSON logger (RISK-015) for security-relevant events

const router = express.Router()
// storeFor(tid): resolve a tenant's Cosmos container through the SILO_READY seam
// (pooled today; a promoted tenant gets its own container with no change here). Every
// tenant-scoped read/write below goes through this, so isolation follows the seam.
const storeFor = (tid) => resolveTenantStore(tid).docs
// Upper bound on rows returned by /db/list. The app subscribes to whole collections
// (e.g. 'forms') and filters client-side, so this cap also bounds what a product view
// can see. A single imported product can carry a large forms catalogue (the CORE spec
// has ~1359 forms), so 1000 silently truncated them. 6000 comfortably covers a realistic
// single-tenant forms library while still guarding the heap/RU budget.
const MAX_LIST = 6000
// Per-page hard cap for the cursor-paged /db/list mode (admin data browser etc.).
const PAGE_MAX = 500
const BATCH_OPS = 96
const FIELD_RE = /^[A-Za-z0-9_.]+$/ // property-name allow-list; prevents SQL structure-injection via where/orderBy fields

const segs = (p) => String(p || '').split('/').filter(Boolean)
const baseKey = (path) => { const s = segs(path); return (s[0] === 'products' && s[1]) ? s[1] : (s[0] || 'root') }
const pkFor = (tid, path) => `${tid}|${baseKey(path)}`
const collOf = (path) => segs(path).slice(0, -1).join('/')
const idFor = (prefix, key) => `${prefix}:${String(key).replace(/[/\\?#]/g, '~')}`
const auditId = () => `aud:${Date.now().toString(36)}-${crypto.randomUUID()}`
const searchText = (data) => Object.values(data || {}).filter((v) => typeof v === 'string').join(' ').slice(0, 4000)
// scopeDoc: defense-in-depth tenant drop. A doc read from `${tid}|base` should already belong
// to tid (the pk embeds the tenant), but a cross-tenant doc is dropped to null here too, so an
// isolation break needs BOTH the partition key AND this check to fail. The single source of the
// read-side tenant boundary — readEntity/readChainHead both go through it (H6).
const scopeDoc = (doc, tid) => (doc && doc.tenantId === tid ? doc : null)
const fieldDiff = (prev, next) => {
  const before = {}; const changed = {}
  const keys = new Set([...Object.keys(prev || {}), ...Object.keys(next || {})])
  for (const k of keys) {
    if (JSON.stringify((prev || {})[k]) !== JSON.stringify((next || {})[k])) { before[k] = (prev || {})[k]; changed[k] = (next || {})[k] }
  }
  return { before, changed }
}

// reconstructStateAtRev — reverse-apply the recorded before/changed diffs from the current
// entity data back to `targetRev`, yielding the entity's domain data AS OF targetRev. Pure:
// no I/O. Powers POST /api/db/restore — the SERVER reconstructs, the client never sends a
// snapshot (so it can't forge a restore payload). A HOLE in the version chain (a missing
// rev) or a DELETE inside the range (op:'delete' has a null diff) makes the pre-change
// values unknowable, so we refuse with { error:'unreconstructable', firstMissingRev }
// rather than best-guess. Never mutates the caller's `currentData`.
function reconstructStateAtRev(currentData, versionsByRev, currentRev, targetRev) {
  const state = { ...(currentData || {}) }
  for (let r = currentRev; r > targetRev; r--) {
    const v = versionsByRev.get(r)
    if (!v || !v.diff) return { error: 'unreconstructable', firstMissingRev: r }
    const before = v.diff.before || {}
    const changed = v.diff.changed || {}
    for (const k of new Set([...Object.keys(before), ...Object.keys(changed)])) {
      // Undo rev r: revert each touched field to its before-value; a field that had no
      // before-value (i.e. was ADDED at r) is removed.
      if (Object.prototype.hasOwnProperty.call(before, k)) state[k] = before[k]
      else delete state[k]
    }
  }
  return { state }
}

async function readEntity(tid, path) {
  try {
    const r = (await storeFor(tid).item(idFor('ent', path), pkFor(tid, path)).read()).resource
    return scopeDoc(r, tid) // defense-in-depth: cross-tenant doc → null
  } catch { return null }
}

// chainHead doc: persistent per-path anchor of the audit hash chain (kind:'chainHead').
// It survives entity deletes, so a path's chain stays unbroken across delete +
// re-create, and it seals the NEWEST event (tail-truncation evidence). Its Cosmos
// _etag rides back into the transactional batch as ifMatchETag, so two concurrent
// writers on the same path can never both extend the chain from the same head —
// the loser's whole batch aborts with 412 and the envelope rebuilds from fresh state.
async function readChainHead(tid, path) {
  try {
    const r = scopeDoc((await storeFor(tid).item(idFor('chn', path), pkFor(tid, path)).read()).resource, tid)
    return r ? { hash: r.hash, etag: r._etag } : null
  } catch { return null }
}

// Read every version doc for ONE entityPath (partition-scoped), keyed by rev. Powers the
// restore reconstruction. A READ — no envelope, no chain write (the no-bare-writes census
// only counts .items.create/upsert/batch and .item().delete/replace, never .items.query).
async function readVersionsForPath(tid, path) {
  const sql = "SELECT c.rev, c.op, c.diff FROM c WHERE c.kind = 'version' AND c.entityPath = @path AND c.tenantId = @tid"
  const { resources } = await storeFor(tid).items.query(
    { query: sql, parameters: [{ name: '@path', value: String(path) }, { name: '@tid', value: tid }] },
    { partitionKey: pkFor(tid, String(path)) },
  ).fetchAll()
  const byRev = new Map()
  for (const r of resources) byRev.set(r.rev, { op: r.op, diff: r.diff })
  return byRev
}

// ─── reads (any authenticated role, tenant-scoped) ───────────────────────────
// Reads require product:read, not just auth (persona isolation): the POLICYHOLDER
// portal persona is authenticated and tenant-bound but must never read the tenant's
// catalog — or another policyholder's record — through the generic data surface. Every
// staff role (VIEWER and up) holds product:read, so this tightens nothing for them.
router.get('/get', requireCapability('product:read'), requireTenant, async (req, res) => {
  const ent = await readEntity(resolveTenantForPrincipal(req.user), req.query.path)
  // Inject the entity's natural id (last path segment) so the client has a stable identifier.
  const id = ent ? segs(ent.path).at(-1) : null
  res.json({ data: ent ? { id, ...ent.data } : null })
})

router.post('/list', requireCapability('product:read'), requireTenant, async (req, res) => {
  const { path, query } = req.body || {}
  const tid = resolveTenantForPrincipal(req.user)
  const params = [{ name: '@coll', value: String(path || '') }, { name: '@tid', value: tid }]
  let where = "c.kind = 'entity' AND c.coll = @coll AND c.tenantId = @tid"
  const opMap = { '==': '=', '!=': '!=', '<': '<', '<=': '<=', '>': '>', '>=': '>=' }
  for (let i = 0; i < (query?.where || []).length; i++) {
    const w = query.where[i]
    if (!FIELD_RE.test(String(w.field || ''))) return res.status(400).json({ error: 'invalid_field', field: w.field })
    const p = `@w${i}`; params.push({ name: p, value: w.value })
    where += w.op === 'array-contains' ? ` AND ARRAY_CONTAINS(c.data.${w.field}, ${p})` : ` AND c.data.${w.field} ${opMap[w.op] || '='} ${p}`
  }
  // Cursor-paged mode: a request carrying pageSize (or a cursor from a prior page)
  // streams the collection page-by-page via a Cosmos continuation token instead of
  // one big TOP read. Hard per-page cap PAGE_MAX; response adds { cursor, hasMore }.
  const paged = query?.pageSize !== undefined || query?.cursor !== undefined
  const limit = paged
    ? Math.min(Math.max(parseInt(query?.pageSize, 10) || 100, 1), PAGE_MAX)
    : Math.min(query?.limit || MAX_LIST, MAX_LIST)
  // SELECT TOP caps Cosmos server-side so fetchAll() never loads more than limit rows into heap.
  let sql = `SELECT ${paged ? '' : `TOP ${limit} `}c.data, c.path FROM c WHERE ${where}`
  for (let i = 0; i < (query?.orderBy || []).length; i++) {
    const o = query.orderBy[i]
    if (!FIELD_RE.test(String(o.field || ''))) return res.status(400).json({ error: 'invalid_field', field: o.field })
    // RISK-008: explicitly constrain direction to ASC or DESC before interpolating into SQL.
    const dir = (o.dir || 'asc').toUpperCase()
    if (!['ASC', 'DESC'].includes(dir)) return res.status(400).json({ error: 'invalid_direction', detail: "orderBy.dir must be 'asc' or 'desc'" })
    sql += `${i === 0 ? ' ORDER BY' : ','} c.data.${o.field} ${dir}`
  }
  if (paged) {
    const iterator = storeFor(tid).items.query(
      { query: sql, parameters: params },
      { maxItemCount: limit, continuationToken: query?.cursor ? String(query.cursor) : undefined }
    )
    const page = await iterator.fetchNext()
    return res.json({
      data: page.resources.map((r) => ({ id: segs(r.path).at(-1), ...r.data })),
      cursor: page.continuationToken || null,
      hasMore: !!page.continuationToken,
    })
  }
  const { resources } = await storeFor(tid).items.query({ query: sql, parameters: params }, { maxItemCount: limit }).fetchAll()
  res.json({ data: resources.map((r) => ({ id: segs(r.path).at(-1), ...r.data })) })
})

// ─── grounding-chunk hook ────────────────────────────────────────────────────
// chunk-shared.cjs is generated by `pnpm build:chunk` (esbuild bundle of
// shared/src/retrieval/chunk.ts). Loaded lazily so the server starts even if
// the bundle is absent (e.g. a fresh clone before `pnpm build`).
let _chunker = null
function getChunker() {
  if (!_chunker) { try { _chunker = require('./chunk-shared.cjs') } catch { _chunker = {} } }
  return _chunker
}

// Build a groundingChunk Cosmos op for the entity being written, or return null
// if the entity type is not chunkable or the chunker is unavailable.
function buildChunkOp(entityType, path, data, pk, tid, now) {
  try {
    const ch = getChunker()
    const s = segs(path)
    const pid = s[0] === 'products' && s[1] ? s[1] : null
    const refId = data.refId || s.at(-1) || ''
    let chunk = null
    if (entityType === 'product') chunk = ch.chunkProduct?.(data)
    else if (entityType === 'coverage' && pid) chunk = ch.chunkCoverage?.(data, pid)
    else if (entityType === 'rule' && pid) chunk = ch.chunkRule?.(data, pid)
    else if (entityType === 'formRule' && pid) chunk = ch.chunkFormRule?.(data, pid)
    else if (entityType === 'ratingProgram' && pid) chunk = ch.chunkRatingProgram?.(data, pid)
    else if (entityType === 'ldTable') chunk = ch.chunkLdTable?.(refId, data)
    else if (entityType === 'rtTable') chunk = ch.chunkRtTable?.(refId, data)
    else if (entityType === 'form') chunk = ch.chunkForm?.(data)
    else if (entityType === 'dictionary') chunk = ch.chunkDictionary?.(data)
    if (!chunk?.id || !chunk?.text) return null
    return {
      operationType: 'Upsert',
      resourceBody: {
        id: idFor('chunk', path), pk, tenantId: tid,
        kind: 'entity', coll: 'groundingChunks',
        entityPath: path, entityType,
        data: { id: chunk.id, text: chunk.text, contentHash: chunk.contentHash, metadata: chunk.metadata, type: entityType, productId: chunk.metadata?.productId || null, updatedAt: now },
        updatedAt: now,
      },
    }
  } catch { return null }
}

// ─── dense-embedding hook (best-effort) ─────────────────────────────────────
// embed.js is loaded lazily (mirrors getChunker) so the server starts even if the
// retrieve bundle or Foundry embeddings are unavailable. Given a set of op batches,
// find every groundingChunks Upsert and attach an int8-quantized embedding of its
// text IN PLACE — so the vector rides the SAME transactional batch as the chunk (no
// separate write, no eventual-consistency gap). A failure is swallowed: chunks are
// simply stored without a vector and the query-time retriever falls back to lexical
// ranking for them. Embeddings are a retrieval-quality enhancement, never a write
// dependency, so an embeddings outage can never fail (or slow to a crawl) a mutation.
let _embed = null
function getEmbed() {
  if (!_embed) { try { _embed = require('./embed') } catch { _embed = {} } }
  return _embed
}
async function attachEmbeddings(opsBatches) {
  const chunkOps = []
  for (const ops of opsBatches) for (const o of ops) {
    if (o?.operationType === 'Upsert' && o.resourceBody?.coll === 'groundingChunks' && o.resourceBody.data?.text) chunkOps.push(o)
  }
  if (chunkOps.length === 0) return
  try {
    const em = getEmbed()
    if (!em.embedBatch) return
    const vecs = await em.embedBatch(chunkOps.map((o) => o.resourceBody.data.text))
    if (!vecs) return
    chunkOps.forEach((o, i) => {
      const q = em.quantize?.(vecs[i])
      if (q) { o.resourceBody.data.embedding = q; o.resourceBody.data.embDims = em.EMBED_DIMS }
    })
  } catch { /* best-effort: leave chunks embedding-less, lexical fallback still ranks them */ }
}

// ─── mutations (EDITOR+, tenant-scoped, atomic) ──────────────────────────────
// Storage-envelope fields the SERVER owns exclusively. A client mutation carries only a
// domain payload (`data`); stripping any client-supplied copy of these keys means a client
// can never smuggle a tenant boundary (or storage metadata) into a write. The server is the
// sole writer of tenantId: it is set from the pk/common envelope below, never from `data`.
const RESERVED_ENVELOPE_KEYS = ['tenantId', 'pk', 'kind', 'coll', 'path']

// Bases the mutation envelope may NEVER write into. `filings` holds the immutable
// create-only filing records (server/lib/filing.js) — allowing envelope writes there
// would let a client drop entity docs into the reserved partition and upsert a
// chainHead that collides with a frozen filing's audit-chain anchor.
const RESERVED_BASES = new Set(['filings'])

function envelope(tid, payload, actor, source) {
  const { op, path, entityType } = payload
  if (RESERVED_BASES.has(baseKey(path))) { const e = new Error('reserved_base'); e.code = 'RESERVED_BASE'; throw e }
  const data = { ...(payload.data || {}) }
  for (const k of RESERVED_ENVELOPE_KEYS) delete data[k]
  const now = new Date().toISOString()
  return async () => {
    const current = await readEntity(tid, path)
    const curRev = current?.rev ?? 0
    if (payload.expectedRev !== undefined && curRev !== payload.expectedRev) { const e = new Error('conflict'); e.code = 'CONFLICT'; throw e }
    // parentId validation: must resolve to an existing same-tenant entity (DEF-0003).
    // parentId is a refId (dots, e.g. "GL.COV.001") but coverage docIds are the
    // dot->dash form of the refId (e.g. "GL-COV-001"; see migrate-to-cosmos.ts and
    // isoImport dashId). The seed bypasses this envelope so the mismatch never bit it,
    // but the import path runs through here — so resolve the parent trying the
    // parentId verbatim AND its dot->dash form. Additive: a genuinely missing parent
    // still fails (neither candidate resolves).
    if (data.parentId && op !== 'delete') {
      const base = segs(path).slice(0, -1)
      const raw = String(data.parentId)
      const candidates = raw.includes('.') ? [raw, raw.replace(/\./g, '-')] : [raw]
      let parent = null
      for (const cand of candidates) {
        parent = await readEntity(tid, [...base, cand].join('/'))
        if (parent) break
      }
      if (!parent) { const e = new Error('invalid_parent'); e.code = 'INVALID_PARENT'; throw e }
    }
    // Tamper-evident hash chain: prevHash comes from the per-path chainHead doc
    // (null for the first event of a path); the event hash seals content + link.
    const head = await readChainHead(tid, path)
    // provenance rides through untouched: it is optional AI/voice-authoring attestation
    // (fleet-sourced model id, citation refs, confidence, authoredBy) that assembleEnvelope
    // conditionally seals into the audit hash (H4). Absent → legacy-identical hash.
    return assembleEnvelope({ tid, path, entityType, op, data, actor, source, now, current, head, provenance: payload.provenance })
  }
}

// assembleEnvelope — the PURE, Cosmos-free core of the mutation envelope: given the
// current entity + chainHead ALREADY READ, build the transactional op batch (entity +
// audit + version + searchIndex + chainHead + optional grounding chunk). Extracted from
// envelope()'s closure verbatim so BOTH write paths (mutate, mutateBatch) and the tests
// exercise ONE code path — an imported entity's genesis version doc is produced here
// exactly as an interactive create's. Deterministic in its inputs: no I/O, no clock
// (`now` is passed in). `data` must already be envelope-key-stripped by the caller.
function assembleEnvelope({ tid, path, entityType, op, data, actor, source, now, current, head, provenance }) {
  const pk = pkFor(tid, path)
  const common = { pk, tenantId: tid }
  const curRev = current?.rev ?? 0
  const rev = curRev + 1
  // op:'update' is a PARTIAL update — shallow-merge the incoming fields onto the
  // existing domain data so a caller that sends only what changed (e.g. the state-
  // footprint editor sending just { states, allStates }) never wipes the rest of the
  // document. Without this, an update REPLACES the whole doc: editing a product's
  // footprint stripped its name/lob/lifecycle and corrupted it. create/delete/restore
  // keep prior semantics (create/restore write verbatim — a restore is a full-state
  // rewind, so it must REPLACE not merge). Merge is shallow: a supplied key replaces
  // its value wholesale (arrays/objects are not deep-merged); absent keys retain their
  // prior value. The merged doc feeds the entity, the version diff, the search index
  // and the grounding chunk so all four stay consistent.
  const prevData = (op === 'update' && current && current.data && typeof current.data === 'object') ? current.data : {}
  const mergedData = { ...prevData, ...data }
  const entityData = { ...mergedData, rev, updatedAt: now, updatedBy: actor }
  // Field diff (before/changed) is shared by the version record AND the audit event,
  // so the audit trail itself carries what changed, not just that something changed.
  const diff = op === 'delete' ? null : fieldDiff(current?.data, mergedData)
  const auditBody = {
    entityPath: path, entityType, op, actor, rev, at: now,
    source: source || null, diff, prevHash: head?.hash ?? null,
    // Conditional: only a provenance-bearing write carries the key, so a write with
    // NO provenance hashes byte-identically to before — the chain is NEVER forked.
    // Today computeAuditHash ignores unknown keys (provenance is not yet in
    // AUDIT_HASH_FIELDS); H4 adds CONDITIONAL sealing so a PRESENT provenance becomes
    // tamper-evident while an ABSENT one keeps hashing identically.
    ...(provenance != null ? { provenance } : {}),
  }
  const hash = computeAuditHash({ tenantId: tid, ...auditBody })
  const ops = []
  if (op === 'delete') ops.push({ operationType: 'Delete', id: idFor('ent', path) })
  else ops.push({ operationType: 'Upsert', resourceBody: { id: idFor('ent', path), ...common, kind: 'entity', path, coll: collOf(path), entityType, rev, data: entityData, updatedAt: now } })
  ops.push({ operationType: 'Create', resourceBody: { id: auditId(), ...common, kind: 'audit', ...auditBody, hash } })
  ops.push({ operationType: 'Upsert', resourceBody: { id: idFor('ver', `${path}:${rev}`), ...common, kind: 'version', entityPath: path, rev, op, diff, actor, at: now, ...(provenance != null ? { provenance } : {}) } })
  ops.push({ operationType: 'Upsert', resourceBody: { id: idFor('idx', path), ...common, kind: 'searchIndex', entityPath: path, entityType, deleted: op === 'delete', text: searchText(mergedData), at: now } })
  // chainHead anchor rides the SAME transactional batch; ifMatchETag serializes
  // concurrent writers per path (see readChainHead).
  const headOp = { operationType: 'Upsert', resourceBody: { id: idFor('chn', path), ...common, kind: 'chainHead', entityPath: path, hash, rev, at: now } }
  if (head?.etag) headOp.ifMatchETag = head.etag
  ops.push(headOp)
  // grounding chunk (non-delete only; same pk → same Cosmos partition → atomic)
  if (op !== 'delete') {
    const chunkOp = buildChunkOp(entityType, path, mergedData, pk, tid, now)
    if (chunkOp) ops.push(chunkOp)
  }
  return { pk, ops, rev }
}

// Commit one envelope with bounded retry on 412 (precondition failure on the
// chainHead ifMatchETag): another writer advanced this path's chain between our
// read and our commit — rebuild the envelope from fresh state (new rev, new
// prevHash) and try again. This serializes the hash chain per path AND fixes the
// lost-update race two concurrent no-expectedRev writers previously had.
async function commitEnvelope(tid, buildEnvelope) {
  let lastDetail = null
  for (let attempt = 0; attempt < 3; attempt++) {
    const { pk, ops, rev } = await buildEnvelope()
    await attachEmbeddings([ops])
    let r
    try {
      r = await storeFor(tid).items.batch(ops, pk)
    } catch (e) {
      if (Number(e?.code) === 412 && attempt < 2) continue
      throw e
    }
    const codes = (r.result || []).map((o) => o.statusCode)
    if (!codes.some((c) => c >= 400)) return { ok: true, rev }
    lastDetail = r.result
    if (!codes.includes(412) || attempt === 2) break
  }
  const err = new Error('batch_failed'); err.detail = lastDetail; throw err
}

router.post('/mutate', requireCapability('product:write'), requireTenant, async (req, res) => {
  const payload = (req.body || {}).payload || req.body
  const actor = { uid: req.user.uid, name: req.user.name }
  const tid = resolveTenantForPrincipal(req.user)
  // Per-tenant PRODUCT quota: creating a new product consumes product entitlement. Enforced
  // on the interactive create only (op:create, entityType:product); bulk import/seed goes
  // through mutateBatch and is governed by the import path's own controls, not this cap.
  if (payload && payload.op === 'create' && payload.entityType === 'product') {
    try {
      const q = await require('./platform-config').checkProductQuota(tid)
      if (!q.ok) return res.status(403).json({ error: 'product_quota_exceeded', used: q.used, max: q.max })
    } catch { /* fail-open on infra error */ }
  }
  try {
    const { rev } = await commitEnvelope(tid, () => envelope(tid, payload, actor, '/api/db/mutate')())
    res.json({ ok: true, rev })
  } catch (e) {
    if (e.code === 'CONFLICT') return res.status(409).json({ error: 'conflict' })
    if (e.code === 'INVALID_PARENT') return res.status(422).json({ error: e.message })
    if (e.code === 'RESERVED_BASE') return res.status(403).json({ error: 'reserved_base', detail: 'filings records are immutable (create-only via /api/filing/generate); the mutation envelope cannot write into this base' })
    res.status(500).json({ error: 'mutate_failed', detail: String(e.message || e) })
  }
})

router.post('/mutateBatch', requireCapability('product:write'), requireTenant, async (req, res) => {
  const payloads = (req.body || {}).payloads || []
  const actor = { uid: req.user.uid, name: req.user.name }
  const tid = resolveTenantForPrincipal(req.user)
  const store = storeFor(tid)
  // Track chunk commits so that on failure the caller can identify partial-commit state (DEF-0013).
  let committedChunks = 0; let totalChunks = 0
  try {
    const byPk = new Map()
    for (const p of payloads) { const b = await envelope(tid, p, actor, '/api/db/mutateBatch')(); if (!byPk.has(b.pk)) byPk.set(b.pk, []); byPk.get(b.pk).push(b.ops) }
    // One batched embeddings call across every chunk op in the whole request (keeps a bulk
    // import/seed to a single embeddings round-trip instead of one per entity).
    await attachEmbeddings([...byPk.values()].flat())
    // A transactional batch can report per-op failures without throwing — treat any
    // op status >= 400 as a failed chunk so a partial commit is never reported as ok.
    const commitChunk = async (chunk, pk) => {
      totalChunks++
      const r = await store.items.batch(chunk, pk)
      if (r.result?.some((o) => o.statusCode >= 400)) { const err = new Error('batch_op_failed'); err.detail = r.result.map((o) => o.statusCode); throw err }
      committedChunks++
    }
    for (const [pk, opsList] of byPk) {
      let chunk = []
      for (const ops of opsList) {
        if (chunk.length + ops.length > BATCH_OPS) { await commitChunk(chunk, pk); chunk = [] }
        chunk.push(...ops)
      }
      if (chunk.length) { await commitChunk(chunk, pk) }
    }
    res.json({ ok: true, count: payloads.length })
  } catch (e) {
    if (e.code === 'CONFLICT') return res.status(409).json({ error: 'conflict' })
    if (e.code === 'INVALID_PARENT') return res.status(422).json({ error: e.message })
    if (e.code === 'RESERVED_BASE') return res.status(403).json({ error: 'reserved_base', detail: 'filings records are immutable (create-only via /api/filing/generate); the mutation envelope cannot write into this base' })
    const partial = committedChunks > 0 && committedChunks < totalChunks
    res.status(500).json({ error: partial ? 'batch_partial' : 'batch_failed', committedChunks, totalChunks, detail: String(e.message || e) })
  }
})

router.post('/vote', requireCapability('product:write'), requireTenant, async (req, res) => {
  const { path } = req.body || {}; const uid = req.user.uid; const tid = resolveTenantForPrincipal(req.user)
  const ent = await readEntity(tid, path)
  if (!ent) return res.status(404).json({ error: 'not_found' })
  const votes = ent.data.votes || { voters: [], count: 0 }
  if (!votes.voters.includes(uid)) { votes.voters = [...votes.voters, uid]; votes.count = (votes.count || 0) + 1 }
  const actor = { uid, name: req.user.name }
  await mutateInternal(tid, { op: 'update', path, data: { ...ent.data, votes }, entityType: ent.entityType }, actor, '/api/db/vote')
  res.json({ ok: true, count: votes.count })
})

router.post('/setNewsPins', requireCapability('product:write'), requireTenant, async (req, res) => {
  const { uid, pinnedHashes } = req.body || {}; const tid = resolveTenantForPrincipal(req.user)
  if (uid !== req.user.uid) return res.status(403).json({ error: 'forbidden' })
  const path = `newsPrefs/${uid}`
  const actor = { uid: req.user.uid, name: req.user.name }
  await mutateInternal(tid, { op: 'update', path, data: { pinnedHashes: pinnedHashes || [] }, entityType: 'newsPrefs' }, actor, '/api/db/setNewsPins')
  res.json({ ok: true })
})

router.post('/presence/join', requireCapability('product:write'), requireTenant, async (req, res) => {
  const { pid } = req.body || {}; const tid = resolveTenantForPrincipal(req.user)
  const { presence } = require('./cosmos')
  await presence.items.upsert({ id: `${tid}:${pid}:${req.user.uid}`, pid: `${tid}:${pid}`, uid: req.user.uid, name: req.user.name, at: Date.now() })
  res.json({ ok: true })
})
router.post('/presence/watch', requireAuth, requireTenant, async (req, res) => {
  const { pid } = req.body || {}; const tid = resolveTenantForPrincipal(req.user)
  const { presence } = require('./cosmos')
  const { resources } = await presence.items.query({ query: 'SELECT c.uid FROM c WHERE c.pid = @pid', parameters: [{ name: '@pid', value: `${tid}:${pid}` }] }).fetchAll()
  res.json({ viewers: [...new Set(resources.map((r) => r.uid))] })
})

// ─── Versions read (PCM-B): one product's change history ─────────────────────
// The WRITE side has always recorded kind:'version' docs atomically with each
// mutation (envelope() above) — this is the dedicated READ. /db/list can never
// return them (its WHERE is kind='entity' and its projection is entity-shaped).
// The partition `${tid}|${productId}` contains exactly the product's subtree,
// so productId scoping is free — no entityPath predicate needed. No ORDER BY:
// the indexing policy of the provisioned container is not owned by this repo,
// and the client sorts newest-first anyway. TOP cap mirrors filing.js's asOf
// reader (2000); histories past the cap return an arbitrary subset — the cap
// is generous for a review drawer, and paging can be added if it ever binds.
router.get('/versions', requireCapability('product:read'), requireTenant, async (req, res) => {
  const pid = String(req.query.productId || '')
  if (!pid) return res.status(400).json({ error: 'productId_required' })
  try {
    const tid = resolveTenantForPrincipal(req.user)
    const limit = Math.max(1, Math.min(parseInt(String(req.query.limit), 10) || 500, 2000))
    const sql = `SELECT TOP ${limit} c.id, c.entityPath, c.rev, c.op, c.diff, c.actor, c.at FROM c WHERE c.kind = 'version' AND c.tenantId = @tid`
    const { resources } = await storeFor(tid).items.query(
      { query: sql, parameters: [{ name: '@tid', value: tid }] },
      { partitionKey: pkFor(tid, `products/${pid}`), maxItemCount: limit },
    ).fetchAll()
    res.json({ data: resources })
  } catch (e) {
    res.status(500).json({ error: 'versions_read_failed', detail: String(e.message || e) })
  }
})

// ─── restore (HI-01): rewind an entity to a past rev via the STANDARD envelope ─────
// A restore is a FORWARD mutation, never a history rewrite: the server reconstructs the
// target state (reverse-applying diffs — reconstructStateAtRev), then commits it through
// the same atomic envelope — new rev, new version doc, hash-chained audit event, op:'restore'
// with restore provenance ({ authoredBy:'restore', restoredFrom }). The chain EXTENDS, never
// bends. The client sends only { path, targetRev, expectedRev } — it can never forge a
// snapshot/payload. expectedRev is the optimistic-concurrency token (stale → 409), so a
// restore built against a stale view is refused, never silently overwriting a newer edit.
router.post('/restore', requireCapability('product:write'), requireTenant, async (req, res) => {
  const { path, targetRev, expectedRev } = req.body || {}
  const tid = resolveTenantForPrincipal(req.user)
  const actor = { uid: req.user.uid, name: req.user.name }
  // Validation fires BEFORE any Cosmos I/O.
  if (!path || typeof path !== 'string') return res.status(400).json({ error: 'path_required' })
  if (!Number.isInteger(targetRev) || targetRev < 1) return res.status(400).json({ error: 'invalid_target', detail: 'targetRev must be a positive integer' })
  try {
    const current = await readEntity(tid, path)
    if (!current) return res.status(404).json({ error: 'not_found' })
    const currentRev = current.rev ?? 0
    // Optimistic concurrency: the client restores against the rev it last saw.
    if (expectedRev !== undefined && currentRev !== expectedRev) return res.status(409).json({ error: 'stale_rev', currentRev })
    if (targetRev >= currentRev) return res.status(400).json({ error: 'invalid_target', detail: 'targetRev must be older than the current rev', currentRev })
    const versions = await readVersionsForPath(tid, path)
    const recon = reconstructStateAtRev(current.data, versions, currentRev, targetRev)
    if (recon.error) return res.status(422).json({ error: 'unreconstructable', firstMissingRev: recon.firstMissingRev })
    // Commit the reconstructed state as a forward restore. expectedRev re-guards a concurrent
    // write landing between our read and the commit (the envelope re-checks → CONFLICT → 409).
    const provenance = { authoredBy: 'restore', restoredFrom: targetRev }
    const { rev } = await mutateInternal(tid, { op: 'restore', path, data: recon.state, entityType: current.entityType, expectedRev: currentRev, provenance }, actor, '/api/db/restore')
    log.info('data', 'restore', { tenantId: tid, path, targetRev, fromRev: currentRev, toRev: rev, actor: actor.uid })
    res.json({ ok: true, rev, restoredFrom: targetRev })
  } catch (e) {
    if (e.code === 'CONFLICT') return res.status(409).json({ error: 'stale_rev' })
    if (e.code === 'INVALID_PARENT') return res.status(422).json({ error: e.message })
    if (e.code === 'RESERVED_BASE') return res.status(403).json({ error: 'reserved_base', detail: 'filings records are immutable' })
    log.error('data', 'restore_failed', { tenantId: tid, path: String(path), targetRev, detail: String(e.message || e).slice(0, 200) })
    res.status(500).json({ error: 'restore_failed', detail: String(e.message || e) })
  }
})

// ─── PROBE endpoint: audit documents (ADMIN + PROBE_MODE=1 only) ─────────────
// Added for Phase 3 fault-injection testing (FAULT-003). Returns raw kind=audit
// documents for a path so the smoke harness can verify the audit write is present.
// Only active when PROBE_MODE=1 is set in the server env — never shipped to prod.
if (process.env.PROBE_MODE === '1') {
  router.get('/audit', requireCapability('audit:read'), requireTenant, async (req, res) => {
    const { path } = req.query
    if (!path) return res.status(400).json({ error: 'path_required' })
    const tid = resolveTenantForPrincipal(req.user)
    const pk = pkFor(tid, String(path))
    const sql = "SELECT * FROM c WHERE c.kind='audit' AND c.entityPath=@path AND c.tenantId=@tid"
    const params = [{ name: '@path', value: String(path) }, { name: '@tid', value: tid }]
    const { resources } = await storeFor(tid).items.query({ query: sql, parameters: params }, { partitionKey: pk }).fetchAll()
    res.json({ ok: true, count: resources.length, items: resources })
  })
}

// Internal mutate for same-process callers (e.g., ai.js persistSummary).
// `source` names the write path in the audit event (defaults to 'internal').
async function mutateInternal(tid, payload, actor, source) {
  return commitEnvelope(tid, () => envelope(tid, payload, actor, source || 'internal')())
}

// ─── audit-chain verification (audit:read) ────────────────────────────────────
// Reconstructs every hash chain in the caller's tenant (or one entityPath via
// ?path=) from prevHash links and verifies content hashes + chainHead anchors.
// Read-only; TENANT_ADMIN / SUPPORT / SUPER_ADMIN via the audit:read capability.
const MAX_VERIFY = 10000
router.get('/audit/verify', requireCapability('audit:read'), requireTenant, async (req, res) => {
  try {
    const tid = resolveTenantForPrincipal(req.user)
    const params = [{ name: '@tid', value: tid }]
    let where = 'c.tenantId = @tid'
    if (req.query.path) { where += ' AND c.entityPath = @path'; params.push({ name: '@path', value: String(req.query.path) }) }
    const fetchKind = async (kind) => (await storeFor(tid).items.query(
      { query: `SELECT TOP ${MAX_VERIFY} * FROM c WHERE c.kind = '${kind}' AND ${where}`, parameters: params },
      { maxItemCount: MAX_VERIFY }
    ).fetchAll()).resources
    const [events, headDocs] = await Promise.all([fetchKind('audit'), fetchKind('chainHead')])
    const heads = new Map(headDocs.map((h) => [`${h.tenantId} ${h.entityPath}`, h.hash]))
    const verdict = verifyAuditChain(events, heads)
    // truncated: MAX_VERIFY hit — verdict may miss chains; narrow with ?path=.
    res.json({ ...verdict, events: events.length, headDocs: headDocs.length, truncated: events.length >= MAX_VERIFY })
  } catch (e) {
    res.status(500).json({ error: 'verify_failed', detail: String(e.message || e) })
  }
})

module.exports = Object.assign(router, { mutateInternal, assembleEnvelope, reconstructStateAtRev, scopeDoc })
