'use strict'
// server/lib/serff.js — SERFF filing bundle REST API.
// Mounted at /api/serff/v1 in server.js.
//
// Endpoints:
//   POST /bundle           — diff two products, assemble a Texas SERFF bundle, run the reviewer lens
//   GET  /states           — return the state filing matrix (read-only; any authed user)
//
// Authentication: platform JWT (auth.attachUser, global in server.js).
//   POST /bundle  — EDITOR+ (generating a filing is a write-class action)
//   GET  /states  — any authed user (VIEWER+)
//
// AI prose generation: the explanation-of-changes memo prose sections are generated by
// Foundry Claude via the fleet BULK_VERIFY role (see ./fleet — single source of deployment
// names + cost guard) and written into the memo's `prose` fields before the bundle is
// returned. The browser NEVER calls the model API directly — all AI is server-side (CLAUDE.md).
//
// Rate exhibit: impacts are computed by the actual evaluate() engine, not estimated,
// using a grid of representative scenarios derived from each line's worked example.

const express = require('express')
const { requireAuth, requireRole, requireTenant } = require('./auth')
const fleet = require('./fleet')   // model routing (single source) + cost guard

const router = express.Router()

// ─── compiled SERFF shared module (built by pnpm build:serff) ─────────────────────
let serff = null
try {
  serff = require('./serff-shared.cjs')
} catch {
  console.warn(
    '[serff-api] serff-shared.cjs not found — ' +
    'run `pnpm build:serff` to generate it. Endpoints will return 503.',
  )
}

// ─── Cosmos tenant-store seam ────────────────────────────────────────────────────────
// Resolve a tenant's container through cosmos.resolveTenantStore (pooled today; SILO_READY).
// Every SERFF read is tenant-scoped, so it flows through the same seam as data.js.
function cosmos(tenantId) {
  return require('./cosmos').resolveTenantStore(tenantId).docs
}

// ─── Cosmos helpers ───────────────────────────────────────────────────────────────

const idFor = (prefix, key) => `${prefix}:${String(key).replace(/[/\\?#]/g, '~')}`
const pkFor = (tid, base)   => `${tid}|${base}`

async function readColl(tenantId, productId, coll) {
  const { resources } = await cosmos(tenantId).items.query({
    query: "SELECT c.data FROM c WHERE c.kind='entity' AND c.coll=@coll AND c.tenantId=@tid",
    parameters: [
      { name: '@coll', value: `products/${productId}/${coll}` },
      { name: '@tid',  value: tenantId },
    ],
  }, { maxItemCount: 500 }).fetchAll()
  return resources.map(r => r.data)
}

async function readEntity(tenantId, path) {
  const base = path.split('/').filter(Boolean)[1] || path
  try {
    const r = (await cosmos(tenantId).item(idFor('ent', path), pkFor(tenantId, base)).read()).resource
    return r?.tenantId === tenantId ? r.data : null
  } catch { return null }
}

/** Load a full ProductSnapshot for a product from Cosmos (all subcollections). */
async function loadSnapshot(tenantId, productId) {
  const productData = await readEntity(tenantId, `products/${productId}`)
  if (!productData) return null

  const [coverages, forms, rtRows, ldRows, ratRows] = await Promise.all([
    readColl(tenantId, productId, 'coverages'),
    readColl(tenantId, productId, 'forms'),
    readColl(tenantId, productId, 'rtTables'),
    readColl(tenantId, productId, 'ldTables'),
    readColl(tenantId, productId, 'ratingPrograms'),
  ])

  const rtTables = Object.fromEntries(rtRows.map(t => [t.refId, t]))
  const ldTables = Object.fromEntries(ldRows.map(t => [t.refId, t]))
  const ratingProgram = ratRows[0] ?? { refId: '', name: '', steps: [], minimumPremium: 0, allStates: true, states: [], status: 'ACTIVE', lifecycle: 'LAUNCHED', reviewStatus: 'APPROVED', updatedBy: '', rev: 1, createdAt: null, updatedAt: null }

  return {
    refId: productData.refId ?? productId,
    name:  productData.name  ?? productId,
    lob:   productData.lob   ?? null,
    coverages,
    forms,
    rtTables,
    ldTables,
    ratingProgram,
  }
}

// ─── Scenario grid builder ─────────────────────────────────────────────────────────
// Builds representative rating scenarios for the rate exhibit. Uses the line's
// worked example as the base and varies the most common rating dimensions.

function buildScenarios(kit, snapshot) {
  const base = { ...kit.workedExample }
  // Extract unique first-dimension values from the largest RT table (territory / class code)
  const tables = Object.values(snapshot.rtTables)
  const firstTable = tables.sort((a, b) => b.rows.length - a.rows.length)[0]
  if (!firstTable || firstTable.rows.length === 0) {
    return [{ label: 'Base worked example', inputs: base }]
  }
  const keyCol = firstTable.columns[0]
  const keyVals = [...new Set(firstTable.rows.map(r => String(r[keyCol])))]
  return keyVals.slice(0, 10).map(v => ({
    label:  `${keyCol}=${v}`,
    inputs: { ...base, [keyCol]: v },
  }))
}

// ─── AI memo prose generator (server-side only) ────────────────────────────────────

async function generateMemoProse(memoContent) {
  if (!fleet.isConfigured()) return memoContent   // return structure-only when AI not configured
  const systemPrompt = [
    'You are a regulatory filing specialist drafting an explanation-of-changes memorandum for a Texas DOI filing.',
    'Write clear, precise, professional prose for each section. Do NOT invent facts, rates, or regulatory citations.',
    'Every claim must be grounded in the provided section items. Be concise — one short paragraph per section.',
    'Do not add emojis. Do not repeat the heading. Output ONLY the prose for the section requested.',
  ].join(' ')

  const enriched = { ...memoContent }
  const sectionsCopy = memoContent.sections.map(s => ({ ...s }))

  for (const section of sectionsCopy) {
    // Cost guard: gate each section call; once the budget ceiling is hit, remaining sections keep
    // their structure-only prose rather than dispatching (bounded spend, no fabrication).
    const g = fleet.guard()
    if (!g.allow) break
    const deployment = fleet.resolveModel('BULK_VERIFY', g.degrade)
    const itemText = section.items.map(i => `${i.label}: ${i.value}${i.citation ? ` [${i.citation}]` : ''}`).join('\n')
    const prompt = `Section: ${section.heading}\n\nItems:\n${itemText}\n\nWrite a short professional paragraph for this section.`
    try {
      const resp = await fetch(fleet.anthropicMessagesUrl(), {
        method:  'POST',
        headers: fleet.anthropicHeaders(),
        body:    JSON.stringify({
          model:      deployment,
          max_tokens: 300,
          system:     systemPrompt,
          messages:   [{ role: 'user', content: prompt }],
        }),
      })
      if (resp.ok) {
        const data = await resp.json()
        fleet.record(deployment, data.usage?.input_tokens, data.usage?.output_tokens)
        section.prose = data.content?.[0]?.text?.trim() ?? ''
      }
    } catch (e) {
      console.warn('[serff-api] AI prose generation failed for section', section.heading, e.message)
    }
  }
  enriched.sections = sectionsCopy
  return enriched
}

// ─── POST /bundle ──────────────────────────────────────────────────────────────────

router.post('/bundle', requireAuth, requireRole('EDITOR'), requireTenant, async (req, res) => {
  if (!serff) return res.status(503).json({ error: 'serff_not_configured', hint: 'run pnpm build:serff' })

  const { cloneProductId, parentProductId, state = 'TX', filingId } = req.body || {}
  if (!cloneProductId || !parentProductId) {
    return res.status(400).json({ error: 'cloneProductId and parentProductId are required' })
  }

  const stateProfile = serff.getStateProfile(state)
  if (!stateProfile) return res.status(400).json({ error: 'unsupported_state', state })

  const tenantId = req.user.tenantId

  // Load both product snapshots from Cosmos
  const [cloneSnap, parentSnap] = await Promise.all([
    loadSnapshot(tenantId, cloneProductId),
    loadSnapshot(tenantId, parentProductId),
  ])
  if (!cloneSnap)  return res.status(404).json({ error: 'clone_not_found',  productId: cloneProductId })
  if (!parentSnap) return res.status(404).json({ error: 'parent_not_found', productId: parentProductId })

  // Diff
  const changeset = serff.diffProducts(parentSnap, cloneSnap)

  // Rate kit — LOB prefix from product.lob.prefix (authoritative) or ratingProgram refId (DEF-0021)
  const lobPrefix = cloneSnap.lob?.prefix || cloneSnap.ratingProgram?.refId?.split('.').filter(Boolean)[0] || null
  if (!lobPrefix) return res.status(400).json({ error: 'unsupported_lob', cloneProductId })
  const kit = serff.resolveRatingKit(lobPrefix)
  const parentRtGetter = kit.makeRtGetter(parentSnap.rtTables)
  const parentLdGetter = kit.makeLdGetter(parentSnap.ldTables)
  const cloneRtGetter  = kit.makeRtGetter(cloneSnap.rtTables)
  const cloneLdGetter  = kit.makeLdGetter(cloneSnap.ldTables)
  const scenarios      = buildScenarios(kit, cloneSnap)

  // Rate exhibit (computed by actual evaluate() engine)
  const exhibit = changeset.summary.hasRateImpact
    ? serff.generateRateExhibit(
        changeset,
        parentSnap.ratingProgram, cloneSnap.ratingProgram,
        parentRtGetter, parentLdGetter,
        cloneRtGetter,  cloneLdGetter,
        scenarios,
      )
    : null

  // Redlines
  const redlines = serff.generateRedlineDocuments(changeset)

  // Memo structure + AI prose
  const memoStructure = serff.buildMemoStructure(changeset, exhibit?.overallImpactPct ?? null, state)
  const memo = await generateMemoProse(memoStructure)

  // Assemble bundle
  const resolvedFilingId = filingId ?? `${state}-${cloneSnap.refId}-${Date.now()}`
  const bundle = serff.assembleSerffBundle({
    filingId:    resolvedFilingId,
    state,
    productRefId: cloneSnap.refId,
    productName:  cloneSnap.name,
    changeset,
    redlines,
    rateExhibit: exhibit,
    memo,
  })

  // Reviewer lens
  const reviewerResult = serff.checkTexasBundle(bundle)

  // Write bundle record atomically via mutation envelope (entity+audit+version+searchIndex) (DEF-0014)
  try {
    const dataRouter = require('./data')
    const actor = { uid: req.user.uid, name: req.user.name ?? req.user.email }
    await dataRouter.mutateInternal(tenantId, {
      op: 'create',
      path: `products/${cloneProductId}/serffBundles/${resolvedFilingId}`,
      entityType: 'serffBundle',
      data: { filingId: resolvedFilingId, state, parentProductId, cloneProductId, reviewerPassed: reviewerResult.passed },
    }, actor)
  } catch (e) {
    console.warn('[serff-api] bundle record write failed (non-fatal):', e.message)
  }

  res.json({ bundle, reviewerResult })
})

// ─── GET /states ──────────────────────────────────────────────────────────────────

router.get('/states', requireAuth, requireTenant, (req, res) => {
  if (!serff) return res.status(503).json({ error: 'serff_not_configured' })
  res.json({ states: serff.STATE_FILING_MATRIX })
})

module.exports = router
